### ISSUE TITLE
As a guardian I would like to disable colors for the citizens in the app so that it does not overstimulate the citizens

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#10]
Images (pictograms) should not be grey scale, but the colors in the application.

**Comment by Eduardsen** [comment]
![Ugeplan - Citizen View No Color – 1](https://user-images.githubusercontent.com/22811754/55877230-cda86580-5b99-11e9-972d-63837e883929.png)

![Ugeplan - Citizen View No Color](https://user-images.githubusercontent.com/22811754/55877096-6d192880-5b99-11e9-8426-ebf393bcf6d0.png)

**Comment by Lortemanden** [comment]
The prototype with the yellow bar is the one that should be implemented by this feature!

**Comment by Lortemanden** [comment]
This has been implemented by making a color settings for the citizens. #64
