### ISSUE TITLE
Giraf Notify Dialog

### ISSUE THREAD

**Issue by Tricky12321** [aau-giraf/weekplanner-OLDUI#104]
**Is your feature request related to a problem? Please describe.**
There is a need for a notify dialog to show information to the user
(Login failed wrong username and password)
**Describe the solution you'd like**
A Dialog

**Describe alternatives you've considered**

**Additional context**

**Comment by Tekrus** [comment]
#94 uses an alert widget, can't this be used?

**Comment by msimon16** [comment]
This is the same as issue #88
