### ISSUE TITLE
As a guardian, I would like a way to add pictograms directly from google so that I can quickly improvise if the system does not have the activity I want

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#11]

**Comment by jenspetur94** [comment]
When searching for pictograms in the app it should be possible to switch to online search to search for pictograms on google 

![image](https://user-images.githubusercontent.com/22811843/53300280-69c61980-3845-11e9-9fda-1531293cf2fd.png)

It should also be possible to switch back to offline search

![image](https://user-images.githubusercontent.com/22811843/53300289-882c1500-3845-11e9-882e-9c2c37d9917e.png)

**Comment by Alechj** [comment]
- [ ] Add button to switch to google api search

- [ ] Implement and query google's search api

- [ ] Parse results to existing gui

**Comment by Tekrus** [comment]
This is replaced by #135
