### ISSUE TITLE
Send user information to weekplan selector involves #47 and #50 

### ISSUE THREAD

**Issue by fryyd** [aau-giraf/weekplanner-OLDUI#113]
Involves #47 and #50 
**Explanation of the dependency**
Conflicting use of UsernameModel and GirafUsernameModel

**Project groups working on this**
The issues involces group SW609f19 and SW613f19.

Group SW609f19 contacted SW613f19, and asked if the ID was the only field used from GirafUsernameModel, since this was the case, the use of GirafUsernameModel was exchange with UsernameModel.

**Screens involved**
The screens invovled are choose_citizen_screen and weekplan_selector_screen

**Comment by fryyd** [comment]
Solved by replacing GirafUserModels with UsernameModel in classes weekplan_selector_screen, weekplands_bloc and in the tests weekplans_bloc_test and weekplan_selector_test.
Then finally adding the call to the WeekplanSelectorScreen passing a user in ChooseCitizenScreen.

**Comment by MStenkaer** [comment]
Merged
