### ISSUE TITLE
As a guardian, I would like to be able to copy the content of a plan in the weekplanner from one user to another so that I won't have to do it twice, if two citizens have the same schedule

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#12]

**Comment by jenspetur94** [comment]
![image](https://user-images.githubusercontent.com/22811843/53321182-f6b9b300-38d7-11e9-877d-34bbdbdf506a.png)

![image](https://user-images.githubusercontent.com/22811843/53321210-0a651980-38d8-11e9-97f6-c28aeb07350a.png)

![image](https://user-images.githubusercontent.com/22811843/53321229-18b33580-38d8-11e9-94e8-aa1f057fd73b.png)

![image](https://user-images.githubusercontent.com/22811843/53321241-236dca80-38d8-11e9-8d46-c6e5343a0a1e.png)

![image](https://user-images.githubusercontent.com/22811843/53321265-34b6d700-38d8-11e9-850a-d17c84e64e30.png)

![image](https://user-images.githubusercontent.com/22811843/53321298-4bf5c480-38d8-11e9-91a2-5009af144e24.png)

**Comment by andpaacoke** [comment]
Duplicate of #63
