### ISSUE TITLE
Logout not redirecting

### ISSUE THREAD

**Issue by LukasRH** [aau-giraf/weekplanner-OLDUI#120]
**Explanation of the dependency**
When clicking the logout button the user gets logged out, but not redirected to the login screen.
Issue #49 states that after logout the user should be redirected to the login screen 

**Project groups working on this**

**Screens involved**
All screens, log out button is in Giraf AppBar

**Comment by Tekrus** [comment]
Approved, whoever is fixing this, remember to assign your entire group to this issue.
