### ISSUE TITLE
As a citizen the appbar should only show the icon "change to guardian mode" icon

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#121]
**Is your feature request related to a problem? Please describe.**
It is related to #55 

**Describe the solution you'd like**
I would like the back button to be removed, and the same with log out and settings icon.

**Describe alternatives you've considered**
None.

**Comment by andpaacoke** [comment]
![Ugeplan - Citizen view – 1](https://user-images.githubusercontent.com/22811754/56269836-ee6e3f00-60f4-11e9-8c9a-94f5c7eff2ee.png)

**Comment by Tekrus** [comment]
@aau-giraf/sw612f19 you have been assigned to this! 🛠
