### ISSUE TITLE
weekdays names written on multiple lines on smaller screens landscape mode

### ISSUE THREAD

**Issue by msimon16** [aau-giraf/weekplanner-OLDUI#124]
related to issue #43 

Would be nice if all weekdays were displayed in a single line in landscape mode

![image](https://user-images.githubusercontent.com/26058779/55623786-4b3c3200-57a4-11e9-9f11-60ea8f6f7d45.png)

**Comment by Tricky12321** [comment]
I would advise you to use the Autosize Text dependency from the project, it will autosize it regardless of screen size
