### ISSUE TITLE
As a citizen i would like to only see the current day of the weekplan when my device is in portrait mode

### ISSUE THREAD

**Issue by andpaacoke** [aau-giraf/weekplanner-OLDUI#126]
This should only be the case for phones and not on tablets

**Comment by andpaacoke** [comment]
![citizen phone portrait](https://user-images.githubusercontent.com/22811754/55872958-a9935700-5b8e-11e9-92af-b1ea9e5a3c2d.png)

**Comment by Lortemanden** [comment]
We no longer support phones
