### ISSUE TITLE
As a user I would like to be able to switch between guardian and citizen mode so that I can only access the parts of the system that I should be able to

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#132]
- [ ] The system stores whether the user is currently in citizen or guardian mode
- [ ] A guardian can see the add new activities function, but a citizen cannot

**Comment by andpaacoke** [comment]
Changing from citizen to guardian dialog
![Ugeplan - Change to guardian password prompt](https://user-images.githubusercontent.com/22811754/55872449-4fde5d00-5b8d-11e9-8afb-e54a57663889.png)
Citizen view
![Ugeplan - Citizen view](https://user-images.githubusercontent.com/22811754/55872469-65538700-5b8d-11e9-8a66-6beeeb7173e6.png)
Guardian view
![Ugeplan - Guardian view](https://user-images.githubusercontent.com/22811754/55872547-90d67180-5b8d-11e9-856c-6590aea96d51.png)
