### ISSUE TITLE
As a guardian, I would like a way to add pictograms by taking a picture from my camera so that I can quickly improvise if the system does not have the activity I want

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#134]

**Comment by Tekrus** [comment]
Consider asking the customers if they still want this if #135 is implemented.

**Comment by andpaacoke** [comment]
Bottom bar where adding a pictogram by taking a picture can be chosen
![Piktogram - Add via photo 2](https://user-images.githubusercontent.com/22811754/57691944-c87d8100-7645-11e9-9cb9-09e13b445403.png)
Screen for adding a pictogram using the camera
![Piktogram - Add via camera](https://user-images.githubusercontent.com/22811754/57691951-cca99e80-7645-11e9-92af-a9f6d371308a.png)

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 134](https://trello.com/c/rbUtV8ld/46-issue-134)
