### ISSUE TITLE
As a guardian, I would like a way to add pictograms by choosing an image from my phone gallery so that I can quickly improvise if the system does not have the activity I want

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#135]

**Comment by Tekrus** [comment]
This replaces #11

**Comment by andpaacoke** [comment]
I should be able to press a button in the bottom bar to open the photo gallery
![Piktogram - Add via gallery](https://user-images.githubusercontent.com/22811754/56794066-adb9a880-680d-11e9-8f04-dd352d1752fd.png)

I should be able to choose a picture from the gallery that i would like to add as a pictogram
![Piktogram - photo gallery](https://user-images.githubusercontent.com/22811754/56793781-0b99c080-680d-11e9-812f-cdf9a6eed31b.png)

The pictogram i choose should be shown in the center and I should be able to name it.
![Piktogram - photo gallery 2](https://user-images.githubusercontent.com/22811754/56793783-0d638400-680d-11e9-982a-6fc7ce43b6f5.png)

When i click the checkmark the new pictogram should be added to the current weekplan and added to the pictograms

**Comment by scarress** [comment]
#243
