### ISSUE TITLE
As a guardian I would like to be able to choose how many days a citizen can see at a time on their weekplanner, so that it fits their personal preference

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#15]
- [ ] I can choose and show 1 day (current day)
- [ ] I can choose and show 5 days (monday-friday)
- [ ] I can choose and show 7 days (monday-sunday)

**Comment by Eduardsen** [comment]
From the settings page the amount of days can be chosen
![AntalDageVist](https://user-images.githubusercontent.com/22811754/57692366-e4355700-7646-11e9-8aac-f550b3c3acac.png)
![Ugeplan - Citizen view 5 days](https://user-images.githubusercontent.com/22811754/57692384-f0211900-7646-11e9-863f-53e336a3f01e.png)
![Ugeplan - Citizen view 3 days](https://user-images.githubusercontent.com/22811754/57692387-f1524600-7646-11e9-8173-657f4c6a35a7.png)
![Ugeplan - Citizen view 1 day](https://user-images.githubusercontent.com/22811754/57692389-f1eadc80-7646-11e9-8d44-9e15853c76a0.png)

**Comment by tdybda17** [comment]
Should these settings be per. weekplan or per. Citizen?

**Comment by tdybda17** [comment]
Well in the web_api we found this in `Models.GirafUser`

```
/// <summary>
/// defines the number of days to display for a user in a weekschedule
/// </summary>
public int? NrOfDaysToDisplay { get; set; }
```
Which I guess answers the question

**Comment by Lortemanden** [comment]
Yes this is per citizen

**Comment by Simon97** [comment]
It has been decided together with the PO group that the option "Tre dage" from the prototype should be ignored.
This means that only the monday-sunday, monday-friday and today-option will be available.
