### ISSUE TITLE
The weekplan screen should reflect changes to the state of activities.

### ISSUE THREAD

**Issue by Alechj** [aau-giraf/weekplanner-OLDUI#150]
**Is your feature request related to a problem? Please describe.**
Right now the weekplan screen does not show if an activity is completed/cancelled etc.

**Describe the solution you'd like**
The weekplan screen should show the apprioriate icons (green checkmark/red X) on activities.

**Describe alternatives you've considered**
I have no alternatives

**Additional context**
This was derived from PR #143

**Comment by andpaacoke** [comment]
![UgeplanCitizen - Completed Checkmark and cancelled](https://user-images.githubusercontent.com/22811754/55877918-91760480-5b9b-11e9-979c-5e6b397e4f14.png)
