### ISSUE TITLE
Unexpected behaviour when signing in as a guardian without any citizens assigned.

### ISSUE THREAD

**Issue by thomaslhansen** [aau-giraf/weekplanner-OLDUI#151]
**Describe the bug**
Error then mapping a citizen avatar to null.

**To Reproduce**
1. Go to the 'app'
2. Sign in with username 'lee' password same as graatand
3. Go to step 4.
4. See error!

**Expected behavior**
Show no citizens and give a short description on how to assign a citizen to a guardian

**Actual behavior**
Red.

**Screenshots**
![image](https://user-images.githubusercontent.com/6441910/55878864-a2c01080-5b9d-11e9-8172-483a3d345aa5.png)

**Environment (please complete the following information):**
- OS: Android and IOS
- Emulator: 10.1 WXGA Tablet API 22 and Pixel 2 API 28
- Physical device: Ipad Pro 11"

**Additional context**
None

**Comment by Lortemanden** [comment]
Not able to find the bug anymore.
OS: Android
Emulator: Pixcel c API 29 and Pixel 2 API 28
Physical device: Samsung galaxy s7
