### ISSUE TITLE
As a guardian I would like to be able to see results as I'm typing the name of a pictogram so that I can see if there are any results instead of just seeing my keyboard

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#16]
Right now the keyboard fills up the entire screen, I would like to know if there are any results when I have written "ca" instead of having to write out "cake" before I see any results

**Comment by Eduardsen** [comment]
![pictosearch](https://user-images.githubusercontent.com/22811794/53241908-6dba3600-36a3-11e9-91ae-6e20d355e0e8.JPG)
