### ISSUE TITLE
Back button on WeekplannerScreen in citizen mode

### ISSUE THREAD

**Issue by rikkereli** [aau-giraf/weekplanner-OLDUI#169]
There should be no back button when you are i citizen mode in the Weekplanner Screen. 
![WeekplanBack](https://user-images.githubusercontent.com/22813786/56656588-2eee2f80-6696-11e9-9fa3-8affb94753b4.png)

**Comment by Tekrus** [comment]
Please use the bug reporting template when reporting bugs. 👍

**Comment by Tekrus** [comment]
Duplicate of #121
