### ISSUE TITLE
Implement functionality to remove weekplans. Related to issue #51.

### ISSUE THREAD

**Issue by Hylet** [aau-giraf/weekplanner-OLDUI#173]
**Is your feature request related to a problem? Please describe.**
When creating a new weekplan it is currently impossible to delete it again.

**Describe the solution you'd like**
I would like to have functionality to delete a weekplan, how and where is a design question that I would like the PO-group to discuss.

**Describe alternatives you've considered**
We don't have any solution as it should be agreed upon by the PO-group.

**Additional context**
This is the screen with weekplans that should be deletable.
![image](https://user-images.githubusercontent.com/18282410/56664155-e2135480-66a7-11e9-84d3-676a9cc29682.png)

**Comment by Tekrus** [comment]
Duplicate of #198
