### ISSUE TITLE
When adding multiple pictograms, only the first is added

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#182]
**Describe the bug**
When adding more pictograms at once, only the first pictogram is saved.

**To Reproduce**
1. Go to a week plan
2. Click add pictogram
3. Add a pictogram
4. Click add pictogram
5. Add a pictogram
6. Go back to choose week plan
7. go back to same weekplan
8.  See error (only first pictogram is shown)

**Expected behavior**
I would expect two or more pictograms to be saved. 

**Actual behavior**
Only the first pictogram is shown.

Related to #52

**Comment by KVISDAOWNER** [comment]
The issue will not meet the release deadline, due to issues with testing. We expect to make it a hotfix to the master, when the release is merged into master.
