### ISSUE TITLE
Loading spinner not show once loading the weekplans for a user. 

### ISSUE THREAD

**Issue by thomaslhansen** [aau-giraf/weekplanner-OLDUI#183]
**Describe the bug**
Once logged in and a user is chosen, the app does not show a loading spinner while waiting for the weekplans to be loaded. 

**To Reproduce**
1. Go to 'Choose citizen'
2. Click on 'Choose a citizen'
3. See error

**Expected behavior**
A loading spinner should be show once the app is waiting for the API to respond. 

**Actual behavior**
Nothing happens before the weekplans are loaded

**Screenshots**
NA

**Environment (please complete the following information):**
Name: 10.1_WXGA_Tablet_API_28 CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 28)

**Additional context**
NA

**Comment by Tricky12321** [comment]
There is no easy way to implement the loading spinner to the screen. There is already a loading spinner on the weekplans pictograms, but not on the entire weekplan selector screen.
