### ISSUE TITLE
Tick mark on week plan screen is not consistent

### ISSUE THREAD

**Issue by Sworgon** [aau-giraf/weekplanner-OLDUI#184]
There is a bug, that makes it so that the tick marks do not display correctly whether the activity is done. This references user story #75.
Procedure to reproduce on the release branch:
1. Add activity to a day in a week plan.
2. Mark the new activity as done.
3. Go back to select week plan screen.
4. Go to the weekplan screen again.
5. Observe that the tick mark on the activity is no more.

**Comment by AlsenDev** [comment]
It sees a lot of the functionality of the weekplan screen was overwritten when #180 was merged into develop.

**Comment by MStenkaer** [comment]
Please do not blame the bug on PR #180, the bug also occurred on branch 'flutter/feature_057_2' before it was merged with develop (Containing the changes from #180) .

**Comment by Alechj** [comment]
This happened to be fixed by pull request #261
