### ISSUE TITLE
Low-res Checkmark icon

### ISSUE THREAD

**Issue by boginw** [aau-giraf/weekplanner-OLDUI#187]
**Describe the bug**
`weekplan_screen` has very low-res "_check_" icon.

**To Reproduce**
1. Login
2. Choose citizen
2. Choose weekplan with tasks completed
4. See check icon

**Expected behavior**
Highres check icon to be displayed

**Actual behavior**
Lowres check icon displayed

**Screenshots**
![Screenshot_20190425-141254](https://user-images.githubusercontent.com/5813142/56735173-0da84480-6765-11e9-9ce8-dd1bdb8bcb23.png)

**Environment (please complete the following information):**
- OS: Android
- Emulator: No
- Phone: Samsung Galaxy Tab S2
- APK Version: 1.0.0

**Additional context**

**Comment by AlsenDev** [comment]
Somehow the checkmark Icon has been changed to an Image, which now uses the asset 'accept.png', which is not a vector, and therefore doesn't scale well.

**Comment by AlsenDev** [comment]
It seems the Icon was overwritten when #180 was merged into develop.

**Comment by MStenkaer** [comment]
Fix merged onto release branch
