### ISSUE TITLE
Inconsistent font size in citizen selection

### ISSUE THREAD

**Issue by scarress** [aau-giraf/weekplanner-OLDUI#194]
**Describe the bug**
The font size in the citizen selector screen, depends on the length of the name. Which could make the screen look messy if there are multiple names with different length.

**To Reproduce**
1. Navigate to the Citizen selector screen. 
2. Font should vary in size, if names of varying length are present. 

**Expected behavior**
Font size should be of same size.

**Screenshots**
![image](https://user-images.githubusercontent.com/23396667/56793362-2c154b00-680c-11e9-9b41-bc5249dc9f25.png)

**Environment (please complete the following information):**
- OS: Windows
- Emulator via IntelliJ
- Phone Nexus 9

**Comment by Tricky12321** [comment]
#197 should solve this
