### ISSUE TITLE
As a citizen I want a time timer so that I know how long is left of my current activity

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#2]
I would like it to look like https://spektrumshop.dk/shop/time-timer-medium-187p.html

**Comment by jenspetur94** [comment]
**Prototyper:**

Der skal være en visuel timer som kan sættes i gang

![image](https://user-images.githubusercontent.com/22811843/53233523-e3b3a280-368d-11e9-9cb6-9e9c1495293b.png)

Når den er sat igang skal den også kunne pauses
![image](https://user-images.githubusercontent.com/22811843/53233582-08a81580-368e-11e9-8e7d-c6117ebfd6b4.png)

Når den er pauset skal den kunne startes igen eller nullstilles
![image](https://user-images.githubusercontent.com/22811843/53233608-15c50480-368e-11e9-9e3b-d771203bf24c.png)

**Comment by andpaacoke** [comment]
is issue #61 identical to this? Also, find out more about how the citizen interacts with the timer

**Comment by andpaacoke** [comment]
![Aktivitet - start timer citizen](https://user-images.githubusercontent.com/22811754/56794735-105f7400-680f-11e9-9275-7aa76bed8a71.png)
![Aktivitet - stop timer citizen](https://user-images.githubusercontent.com/22811754/56794738-1190a100-680f-11e9-974e-a6bb79c58b64.png)
