### ISSUE TITLE
As a guardian I would like for the week plans to be sorted consistently every time I look at the week plans for a specific citizen

### ISSUE THREAD

**Issue by Eduardsen** [aau-giraf/weekplanner-OLDUI#200]
Right now the week plans are sorted randomly. These should be consistent every time the guardian chooses a citizen. They should be sorted by how recently they were made, so the newest ones are first.

**Comment by mathiasandresen** [comment]
mangler tests

**Comment by Laexander** [comment]
Requirement for sorting the weekplans have changed so it is based on the date with the lower date being first. So if you have two weekplans one for year 2000 and one for 2020, the one for 2000 is first
