### ISSUE TITLE
As a guardian I would like to be able to edit weekplan details (name, picture) so that I can fix mistakes I made

### ISSUE THREAD

**Issue by Fatdet** [aau-giraf/weekplanner-OLDUI#202]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to change the name or image of a weekplan

**Describe the solution you'd like**
I would like to somehow get in to an edit menu of sorts where I can change the image and name of the weekplan

**Describe alternatives you've considered**
no

**Additional context**
null

**Comment by andpaacoke** [comment]
![Ugeplaner - Tilføj – 1](https://user-images.githubusercontent.com/22811754/57691793-6b81cb00-7645-11e9-9bd5-9b1b21c63fb4.png)

**Comment by antonhpalmer** [comment]
Vi har to forskellige udkast til hvordan vi kan implementere en `Edit` knap til at rename og ændre billede. Uanset designvalg skal begge knapper lede til ovennævnte prototype. Hvilken løsning hælder i mest til? @aau-giraf/sw613f20 

![image](https://user-images.githubusercontent.com/33866635/74934467-94aa6580-53e6-11ea-829f-32d945837f03.png)

![image](https://user-images.githubusercontent.com/33866635/74934475-996f1980-53e6-11ea-89f2-2d14d926b391.png)

**Comment by holyfailer** [comment]
Hey knappen skal ligge i bunden ved siden af skraldespanden

**Comment by mathiasandresen** [comment]
Der mangler tests på

**Comment by klogeat** [comment]
The feature is implemented only tests are missing
