### ISSUE TITLE
API Exceptions are thrown everywhere where an api call was made previously when the log out button is pressed

### ISSUE THREAD

**Issue by jenspetur94** [aau-giraf/weekplanner-OLDUI#206]
**Describe the bug**
The api throws exceptions everywhere where the api was called in blocs when the user presses the log out button.

**To Reproduce**
1. Go to WeekplanScreen
2. Click on log out button
4. there are multiple API exceptions thrown

**Expected behavior**
The API shouldn't throw exceptions

**Actual behavior**
The API throws exceptions

**Screenshots**
![image](https://user-images.githubusercontent.com/22811843/56802921-984e7980-6821-11e9-9c8d-4b2cd1d3e242.png)

**Comment by boginw** [comment]
The API throws these exceptions because the user is no longer logged in, and as such, does not have access to the endpoints it is trying to hit.

**Comment by Mustafa-ALD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 206](https://trello.com/c/45SetPfh/25-issue-206)

**Comment by Emil7370** [comment]
Bug could not be recreated

**Comment by Mustafa-ALD** [comment]
Closing this issue, because issue #638 makes this issue obselete.
