### ISSUE TITLE
When logging in after logging out there is thrown an exception when the loading spinner is popped

### ISSUE THREAD

**Issue by jenspetur94** [aau-giraf/weekplanner-OLDUI#207]
**Describe the bug**
If you log out and then log in again there is thrown an issue because the loading spinne widget is pop'ed with a outdated context. 

**To Reproduce**
1. Go to choose citizen screen
2. Click on log out button
3. Log in again
4. See exception

**Expected behavior**
It doesn't throw an exception

**Actual behavior**
it throws an exception

**Comment by EsbenNedergaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write tests for #207 (login)](https://trello.com/c/jN0HGAuz/13-write-tests-for-207-login)

**Comment by EsbenNedergaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Identify the problem with logging in #207 (check if it is becaue of the exception thrown when logging out #319)](https://trello.com/c/DJUiZwat/9-identify-the-problem-with-logging-in-207-check-if-it-is-becaue-of-the-exception-thrown-when-logging-out-319)
