### ISSUE TITLE
Giving wrong credentials will crash the app

### ISSUE THREAD

**Issue by TobiasPalludan** [aau-giraf/weekplanner-OLDUI#209]
**Describe the bug**
When logging in, and giving wrong credentials, the app will crash

**To Reproduce**
1. On the login screen.
2. Write wrong credentials (or none)
3. Press login
4. When prompted with wrong credentials, press ok - then it crashes

**Expected behavior**
Show the login screen again and not a black screen

**Actual behavior**
Shows a black screen

**Environment (please complete the following information):**
- OS: iOS
- Phone iPad Pro

**Comment by jenspetur94** [comment]
probably something to do with the loading spinner and how it is popped

**Comment by Tricky12321** [comment]
#211 should fix this
