### ISSUE TITLE
As a guardian I would like a visual representation of where the pictogram I'm dragging is going to end up on the weekplan so that I can easily place it correctly

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#219]

**Comment by andpaacoke** [comment]
It should indicate where the pictogram will be when dragging it between pictograms
![Ugeplan - Guardian view – Drag n drop – 2](https://user-images.githubusercontent.com/22811754/57691309-28732800-7644-11e9-9d36-7c0f46ac55a0.png)
![Ugeplan - Guardian view – Drag n drop](https://user-images.githubusercontent.com/22811754/57691313-2a3ceb80-7644-11e9-9d4d-743506f830cc.png)
![Ugeplan - Guardian view – Drag n drop – 1](https://user-images.githubusercontent.com/22811754/57691317-2c06af00-7644-11e9-811e-db936a2b92bf.png)

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 219](https://trello.com/c/k9flC422/47-issue-219)

**Comment by Mustafa-ALD** [comment]
The code that has to be changed, is written specifically for it's purpose, meaning that it is not future proof, in the sense that it is hard to manipulate and add features to it. More specifically there are a lot of nested return statements, some places there are three nested return statements(Line 331,340,336). Therefore we recommend that there should be done a refactor for this code, before it is worked on.

Files that might be involved in this issue:
weekplan_plan_column.dart (Line 202-412)
weekplan_bloc.dart (Line 204 - 237)

**Comment by Mustafa-ALD** [comment]
update: there are places with 5 nested return statements
https://github.com/aau-giraf/weekplanner/blob/d513b59e2a2cd29eaf61b7443409e1acc9ce8975/lib/widgets/weekplan_screen_widgets/weekplan_day_column.dart#L203-L251
