### ISSUE TITLE
As a guardian I would like to be able to create a choice board so that I can create an activity where the citizen can make a choice between multiple activities

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#220]
The guardian should be able to add multiple activities, from which the citizen can choose which one they want to do.

When the activity is chosen, it should be shown on the week plan as a regular activity/pictogram.

**Comment by andpaacoke** [comment]
Show activity with add choiceboard button
![Vis aktivitet - med choiceboard](https://user-images.githubusercontent.com/22811754/57691114-9703b600-7643-11e9-903b-85e4cb3ae146.png)
Able to add more activities to the choiceboard
![image](https://user-images.githubusercontent.com/55434783/77412307-ff700780-6dbd-11ea-8379-84a22393762f.png)
View of choiceboard in the weekplan as guardian
![Ugeplan guardian - choiceboard](https://user-images.githubusercontent.com/22811754/57691124-9b2fd380-7643-11e9-9374-9bb786bf3dad.png)
View of choiceboard in the weekplan as citizen
![Ugeplan citizen - choiceboard – 1](https://user-images.githubusercontent.com/22811754/57691126-9cf99700-7643-11e9-8b9b-c2194382d241.png)
Choosing activity in the choiceboard
![Ugeplan citizen - choiceboard](https://user-images.githubusercontent.com/22811754/57691129-9e2ac400-7643-11e9-854e-d801f0293848.png)
The chosen activity is shown in the weekplan
![Ugeplan citizen - choiceboard – 2](https://user-images.githubusercontent.com/22811754/57691133-9f5bf100-7643-11e9-9af8-44b2e40660d4.png)

**Comment by T-Dawq** [comment]
Gruppe 14 arbejdede med dette i Sprint 2
De havde nogle problemer med integration tests, der ikke virkede.
De vil gerne arbejde med dette i Sprint 3.
