### ISSUE TITLE
As a guardian I would like to be able to lock a citizens timer so that they can not pause or stop them once they are started.

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#221]
**Is your feature request related to a problem? Please describe.**
Some citizen can't manage having control over the timer and will stop or reset it so they never would get the activity done.
**Describe the solution you'd like**
There should be a option to lock the timer for the citizen in the setting screen as shown below with the "Lås tidsstyring" button. 
![image](https://user-images.githubusercontent.com/55434783/78662962-9fa35180-78d1-11ea-9093-673cfb31003d.png)
 
When the timer is locked the citizen should see the following if there is a set timer that has not been started. The citizen should still be able to start the timer. 
![image](https://user-images.githubusercontent.com/55434783/78663238-0a548d00-78d2-11ea-9017-d7ce54600099.png)

When the timer starts the button should disappear as shown below.
![image](https://user-images.githubusercontent.com/55434783/78663302-2a844c00-78d2-11ea-89a3-2b70bfdc0b61.png)

The button should not return even when the timer is finished. 
![image](https://user-images.githubusercontent.com/55434783/78663390-51db1900-78d2-11ea-99ef-4a62a824cfca.png)

**Additional context**
Some of the other settings shown in the settings screen might not have been implemented. That is not a part of this issue.

**Comment by andpaacoke** [comment]
![Create timer - time timer](https://user-images.githubusercontent.com/22811754/57691003-59069200-7643-11e9-88a2-2d8744080923.png)

**Comment by Lortemanden** [comment]
Has a connection to issue#222
