### ISSUE TITLE
As a guardian I would like to be able to choose different time representations for the timer so that it fits the users preference

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#222]
**Is your feature request related to a problem? Please describe.**
Citizens want different time representations since some of them might not be able to manage the default option.
**Describe the solution you'd like**
There should be a option to change the timer representations for the citizen in the setting screen as shown below with the "Tidsrepræsentation" button.  
![image](https://user-images.githubusercontent.com/55434783/78663861-2dcc0780-78d3-11ea-901c-6dd99869305c.png)

When the button is clicked a menu as shown below should appear where it's possible to choose the different time representations.  
![image](https://user-images.githubusercontent.com/55434783/78666124-2f97ca00-78d7-11ea-9358-d652df70a2eb.png)

The timer representation should change for the activity to match the settings. There is quite a bit of work to get the different representations to work. The hourglass needs to act like the circle and sand should gradually fill up in the bottom and become sparse in the top.   

**Additional context**
Some of the other settings shown in the settings screen might not have been implemented. That is not a part of this issue.

**Comment by andpaacoke** [comment]
![Choose representation 1](https://user-images.githubusercontent.com/22811754/57360452-7a1a3f00-717a-11e9-9de5-c858e0e09905.png)

**Comment by Lortemanden** [comment]
Has a connection to issue #221

**Comment by Lortemanden** [comment]
Group 10 has worked with this in sprint 2.
It is made but the backend could not support it, so they had to update the backend. Now it just needs to be implemented 
Group 10 would like to work with this in sprint 3.
