### ISSUE TITLE
As a guardian, I would like to have the citizens in folders on "Vælg borger" screen, so that I can easily find the correct citizen

### ISSUE THREAD

**Issue by MathiasLybech** [aau-giraf/weekplanner-OLDUI#223]
You should be able to create new folders on the screen where you choose the folder. You should also be able to choose a folder and see the citizens within that folder.

Edit: See comment from 06.05.2020.

**Comment by Tekrus** [comment]
It should be easy to move citizens from one folder to another, as they often change from one class to another.

**Comment by andpaacoke** [comment]
Prototype that shows how a class is chosen before choosing a citizen
![Vælg klassefolder](https://user-images.githubusercontent.com/22811754/57449020-22073980-725b-11e9-9956-1aedcfa02cd7.png)
When editing a citizen, it should be possible to move the citizen to another class
![Ændr borger](https://user-images.githubusercontent.com/22811754/57449035-29c6de00-725b-11e9-9541-2f0c3113b8ed.png)

**Comment by T-Dawq** [comment]
Gruppe 9 arbejdede på dette i Sprint 2, men ønsker ikke at arbejde med dette i Sprint 3.

**Comment by T-Dawq** [comment]
Forår 2020 Sprint 3: Opdel issuet i mindre issues, som oprettes på GitHub. Husk at linke issues til hinanden og til dette issue.

**Comment by Lortemanden** [comment]
This has been split up into smaller issues and this issue is no longer needed.
