### ISSUE TITLE
Create standardised colours for the application

### ISSUE THREAD

**Issue by AlsenDev** [aau-giraf/weekplanner-OLDUI#226]
**Is your feature request related to a problem? Please describe.**
In multiple pull requests, the Giraf colours are created using the .fromRGB() function. These should be standardised. 

**Describe the solution you'd like**
Add the colours to assets as some sort of global variable.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by andpaacoke** [comment]
Closing this as #228 has been created
