### ISSUE TITLE
As a guardian, I would like the search for pictograms to be ordered by how popular a pictogram is, so that I can find the most commonly used pictogram quickly

### ISSUE THREAD

**Issue by MathiasLybech** [aau-giraf/weekplanner-OLDUI#227]
Each pictogram should have a hit counter for how often it is used. It should not be shown to the user, but just be used internally to order the pictograms.

This should be a global counter and not per guardian.

See comments for clarification

**Comment by Kaliahh** [comment]
When creating a new activity, the guardian is currently met with a blank screen and a search bar.

The guardian should instead see the search bar, and the X most used pictograms for the citizen should be displayed below.

**Comment by Kaliahh** [comment]
The pictograms should be sorted by the most popular across the institution by default. They want the children's plans to look alike, so they want to use the same pictograms.

There should be an option to also sort by the most popular for the given citizen.
