### ISSUE TITLE
As a developer i would like to have standardised colors for the application so that i can easily add the correct colors to my widgets.

### ISSUE THREAD

**Issue by andpaacoke** [aau-giraf/weekplanner-OLDUI#228]
- [ ] Add the colors to assets as some sort of global variable.

- See the design guide in the wiki for the different color values

**Comment by andpaacoke** [comment]
This user story is created as a result of the feature request #226

**Comment by jollycola** [comment]
The styling of the whole app should be written in CSS

**Comment by elaurs** [comment]
So there are some different ways to solve this issue:

1. To create a file with all color codes, which can be used in the other files. However if we want to support more dynamic theme changes in the future, this will not be ideal.

2. To support future extensions such as dynamic theming and global state changes, we can wrap the entire widget tree with an InheritedWidget containing color scheme information, config. information etc. That can be manipulated dynamically and is directly accessible to all (grand)child widgets. From an architectural standpoint the placement of the inherited widget in the tree should be considered carefully.

3. Else a better solution, unless our version restrictions are critical to the app, would be to tighten the restriction (from `>=2.1.0 <3.0.0` to `>=2.7.0 <3.0.0`) on the dart SDK version in pubspec.yaml. This allows us to extend classes including ColorScheme with arbitrary extensions e.g. customisable themes and structure without any architectural changes.
