### ISSUE TITLE
When mark mode is active in WeekPlanScreen and you switch to citizen mode mark mode is still active

### ISSUE THREAD

**Issue by ChristianBroS** [aau-giraf/weekplanner-OLDUI#229]
**Describe the bug**
When you tap the edit button to enter mark mode and you switch to citizen mode, then mark mode is still active.

**To Reproduce**
1. Go to any WeekPlanScreen (doesn't matter which).
2. Click on the edit button.
3. Switch to citizen mode.
4. See that mark mode is still active.

**Expected behavior**
If mark mode is active when you switch to citizen mode, then mark mode should become inactive.

**Actual behavior**
Mark mode is still active after switching to citizen mode.

**Comment by LukasRH** [comment]
This is fixed in #230
