### ISSUE TITLE
As a guardian I would like to be able to access parts of the system through the top bar so that I can easily go to the screen I want

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#23]
I especially want access to settings and changing between guardian and citizen mode.

Tasks:

- [x] Press the cogwheel button to go to settings page
- [x] Update icons to fit design guide

**Comment by sipman** [comment]
This feature is somewhat implemented, the UI part is there. But it has the wrong icons and also it lacks all the functionality.
