### ISSUE TITLE
Week names split into multiple lines if the display resolution is not high enough

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#233]
Originally reported in #124 

![image](https://user-images.githubusercontent.com/21969475/57214203-815e1300-6fe9-11e9-932e-a6e3c93b0800.png)

The text should always be shown on one line, as the line break may confuse the citizens and result in them not recognizing the word.

**Comment by AlsenDev** [comment]
A tip to anyone who is assigned this: Use the _AutoSizeText_ class for the text, and set _maxlines_ to 1. Then play around with the max and min font sizes. 🙆‍♂

**Comment by jkrod** [comment]
The pull request #313 didn't automatically close this issue, so I will do it manually

**Comment by T-Hauge** [comment]
test not needed, since the auto size for the text with maxLines keeps the text on a single line
