### ISSUE TITLE
Unlimited Setting Screens

### ISSUE THREAD

**Issue by Sworgon** [aau-giraf/weekplanner-OLDUI#237]
From the settings screen, you can press the settings button and go to another settings screen. This means that two settings screens are open. From the second settings screen you can open a third. As time passes, there will be a substantial amount of settings screen in a stack. Because of this, it takes a while to pop all of the settings screens. One easy way to fix this bug is to remove the settings button from the app bar in the settings screen.

**Comment by Simon97** [comment]
This issue should be closed since it is not a problem in the current version
