### ISSUE TITLE
Show error on pictogram upload failed

### ISSUE THREAD

**Issue by scarress** [aau-giraf/weekplanner-OLDUI#245]
**Is your feature request related to a problem? Please describe.**
Currently when a Pictogram is uploaded, no feedback is given if an error ocours.

**Describe the solution you'd like**
Something like a pop-up or modal window saying success or giving an error message.

**Comment by Moesgaarda** [comment]
Blocked by #243 - will be part of 2019S4R2 if this is fixed

**Comment by holyfailer** [comment]
![errorMsgUploadPictogram](https://user-images.githubusercontent.com/55434839/76610798-c2805700-6519-11ea-980c-9cf04a3e54e6.PNG)


Dont worry about the slightly different background. Just keep as is.

If possible you can add what kind of error that happened to the text(no internet etc) that would be great, but keep it simple.

**Comment by Lortemanden** [comment]
Group 8 has worked with this in sprint 1.
It is solved but the group did not make a pull request in time for sprint 1
Group 8 would like to work with this in sprint 2.
