### ISSUE TITLE
Text in the input field for timer

### ISSUE THREAD

**Issue by andpaacoke** [aau-giraf/weekplanner-OLDUI#254]
**Describe the bug**
When creating a timer you can enter letters in the input fields. You are however not allowed to create the timer, but no feedback is given to the user. If you enter letters in one field and numbers in another, you can still create the timer.

**To Reproduce**
1. Go to an activity's page and add press the add timer button and enter some text in the field 
2. Click on the checkmark
3. No error is shown to the user

**Expected behavior**
Either a dialog should be shown to the user that they can't create a timer with text as input, or they should not be allowed to enter text at all

**Actual behavior**
Nothing really happens

This was done on an emulator

**Comment by andpaacoke** [comment]
Only possible on emulator so it isn't relevant

**Comment by msimon16** [comment]
Issue still relevant. Some devices have letters or symbols in the "number-keyboard", and should be checked
