### ISSUE TITLE
Overflow and multiple lines in edit mode on smaller device

### ISSUE THREAD

**Issue by Last16** [aau-giraf/weekplanner-OLDUI#255]
**Describe the bug**
When on a smaller device, the edit mode used to mark activities has several overflows. When entering edit mode, the button bar in the bottom has overflow, so only half the delete button is visible. The dialogs when tapping the cancel and delete buttons have a slight overflow on the confirm buttons. When tapping the copy button, the name of the weekdays are all split over 3-4 lines.

**To Reproduce**
1. Go to 'Weekplanner screen'
2. Click on 'Edit mode' and also check each button on the button bar in the bottom. 
3. See error

**Expected behavior**
No overflow and more readable weekday names.

**Actual behavior**
Overflow and difficult to read weekdays

(Ignore slider in left bottom corner on screenshot 2, it's a screenshot feature)

**Screenshots**
![60111508_1035027116699257_7303692908773769216_n](https://user-images.githubusercontent.com/22813275/57612878-eed3eb80-7575-11e9-85b1-b0962033312b.jpg)
![60029452_378139436132488_5527006835548094464_n](https://user-images.githubusercontent.com/22813275/57612879-eed3eb80-7575-11e9-8327-a058e0e24907.jpg)
![60338217_308752153374290_6980941720095555584_n](https://user-images.githubusercontent.com/22813275/57612880-eed3eb80-7575-11e9-9d8c-033066b7b8b2.jpg)
![60185454_339414566775348_498926314753884160_n](https://user-images.githubusercontent.com/22813275/57612882-ef6c8200-7575-11e9-8301-86f0348be4fe.jpg)

**Environment (please complete the following information):**
- OS: [Android]
- Phone [Samsung Galaxy A8]

**Comment by Tekrus** [comment]
Since we don't focus on phones at this point, I've labeled it as a regular bug instead.

**Comment by Lortemanden** [comment]
Is this a problem on our minimum supported resolution?

**Comment by christianhurley** [comment]
Issue will be closed. The minimum required screen for this project as of now will not have this problem, 600x1024 mdpi, this was tested thoroughly.
