### ISSUE TITLE
Timer is not saved on ShowActivityScreen

### ISSUE THREAD

**Issue by LukasRH** [aau-giraf/weekplanner-OLDUI#256]
**Describe the bug**
The timer on the activity screen does not seem to be saved to the database, After adding a timer, and restarting the app the timer is gone.

**To Reproduce**
1. Go to any activity
2. Add a new timer
3. Go back to choose citizen screen or restart the app
4. Go back to the same activity
5. The timer is now gone

**Expected behavior**
The timer should be showed

**Actual behavior**
The timer is not showed 

**Environment (please complete the following information):**
- OS: [Android Pi]
- Emulator
- Phone [Pixel C]

**Comment by Tekrus** [comment]
Confirmed, should be fixed

**Comment by fryyd** [comment]
Did you run the web-api on the master branch when this bug occoured?

**Comment by LukasRH** [comment]
> Did you run the web-api on the master branch when this bug occoured?

I used http://srv.giraf.cs.aau.dk/DEV/API

**Comment by fryyd** [comment]
> > Did you run the web-api on the master branch when this bug occoured?
> 
> I used http://srv.giraf.cs.aau.dk/DEV/API

Seems like the new upates is not migrated to develop :s
