### ISSUE TITLE
As a guardian I would like an error message to be shown if I try to log in while I'm offline so that I know that I'm offline

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#265]
Right now it results in a "forkert password eller brugernavn" error.

This should instead inform the user that they are offline.

**Comment by Lortemanden** [comment]
Related to issue #9

**Comment by Lortemanden** [comment]
![image](https://user-images.githubusercontent.com/55434783/76606426-84cc0000-6512-11ea-83c2-73085acbeff6.png)

**Comment by Lortemanden** [comment]
This has been fixed
