### ISSUE TITLE
As a guardian I would like to be able to edit a text to a pictogram in a weekplan so that other guardians know what I mean by it

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#266]
There have been added some text to activities so the guardians can communicate with each other and the citizens about the activities. The guardians want to be able to change the text shown under the activities as shown in the image below. 

Right now it takes the name of the pictogram and uses as the standard text. This should still be the same and when the button hent standard is pressed this text should show up in the text field.

The button gem til borger should save the text in the field so the text for the activity changes to whats written in the field. It should also save the text so that all activities in the future that uses this pictogram for this citizen automatically gets this text instead of the standard text. Be aware that this saved text is specific for the citizen and only applies to activities that uses the pictogram in the future, not current activity that uses the pictogram.   
![image](https://user-images.githubusercontent.com/55434783/81390284-73bafc00-911b-11ea-86a8-147e976cdbd1.png)

**Comment by EsbenNedergaard** [comment]
This issue depends on #267 because this issue is where the text to the pictograms are added.
