### ISSUE TITLE
It should be more clear that a pictogram should be chosen when creating a new weekplan.

### ISSUE THREAD

**Issue by andpaacoke** [aau-giraf/weekplanner-OLDUI#275]
- Change the icon to the icon from the icon guide

- There should be some text that indicates that a pictogram should be chosen

**Comment by Tekrus** [comment]
The icon will be added with #243

**Comment by AlsenDev** [comment]
Description added to card.

![image](https://user-images.githubusercontent.com/14176903/57684980-2eaed780-7637-11e9-9d06-9736db4adf7a.png)
