### ISSUE TITLE
Activity timer is very CPU heavy

### ISSUE THREAD

**Issue by AlsenDev** [aau-giraf/weekplanner-OLDUI#284]
**Describe the bug**
When starting a timer under an activity, the CPU usage will quickly rise to 100%. 

**To Reproduce**
1. Start a timer on any activity
2. Enjoy your new space heater

**Expected behavior**
Not using all of the CPU.

**Actual behavior**
Using all of the CPU.

**Screenshots**
![image](https://user-images.githubusercontent.com/14176903/57694073-1a74d580-764b-11e9-86c3-252003626692.png)

**Environment (please complete the following information):**
- OS: Windows 10 Pro
- Emulated on a Pixel C tablet
- Branch: 2019S4R1

**Comment by fryyd** [comment]
This can be fixed in the timer_bloc by changing the value of the updatePeriod to something more suitable, like 1 second.
