### ISSUE TITLE
A new timer cannot be started if old one is deleted but not stopped

### ISSUE THREAD

**Issue by mathiasandresen** [aau-giraf/weekplanner-OLDUI#301]
**Describe the bug**
When a timer is done, it is not stopped, and when deleting the timer without stopping it, a new one cannot be started without stopping it first.

**To Reproduce**
1. Go to activity
2. Start a timer with 5 seconds
3. Let it finish and delete it without stopping it
4. Create a new timer
5. Error: The new timer cannot be started

**Expected behavior**
The timer should stop when it is done, and should stop if it is deleted.

**Actual behavior**
The timer does not stop, and when it is deleted it does stop, and a potential new timer cannot be started.

**Screenshots**
![Screenshot_2020-02-25-15-34-56](https://user-images.githubusercontent.com/5781825/75256503-d589ec00-57e3-11ea-8cda-bb8c2c9bb0f6.png)

**Environment (please complete the following information):**
- OS: Android 4.4.4
- Emulator: No
- Samsung SM-T560 (Tablet)

**Comment by Lortemanden** [comment]
We have tried to reproduce the bug and we have no problem deleting and starting a new timer on both emulator and phone. Is this bug happening for multiple people in your group @jollycola?

**Comment by mathiasandresen** [comment]
seems to be fixed
