### ISSUE TITLE
The 'add new weekplan'-button is still available in edit-mode, but does nothing.

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#304]
**Describe the bug**
After navigating to a list of weekplans belonging to a citizen, if the 'edit'-button is pressed the 'add new weekplan'-button remains available and unchanged. This indicates that pressing it in 'edit'-mode will have some sort of effect but it has no effect. 

**To Reproduce**
1. Choose a citizen to show all weekplans of this citizen.
2. Press the 'edit'-button and notice how the 'add new weekplan'-button does not change.
3. Press the 'add new weekplan'-button and notice how nothing happens.

**Expected behavior**
'Add new weekplan'-button should still work in edit-mode as it does in normal-mode, but when a new weekplan is made, it should return to the page with all the weekplans, but still in edit-mode.

**Actual behavior**
'Add new weekplan'-button remains unchanged and seemingly active even though pressing it has no effect.

**Screenshots**
See video in .zip file.
[EditWeekplanBug.zip](https://github.com/aau-giraf/weekplanner/files/4257654/EditWeekplanBug.zip)

**Environment (please complete the following information)**
Observed in emulator.

**Comment by Lortemanden** [comment]
The tilføj ugeplan button should not be removed when in edit mode but be disabled(set opacity to 40%).
