### ISSUE TITLE
As a guardian i want the timer's play-button to function as a restart-button when the timer has finished

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#307]
**Is your feature request related to a problem? Please describe.**
When the timer has finished counting down, the pause symbol is still displayed on the play/pause-button. If it is pressed, the play symbol is displayed. Press it again and the symbol switches to the pause symbol but nothing happens with the timer.

**Describe the solution you'd like**
When the timer has finished, the pause symbol should automatically switch to a play symbol on the play/pause-button. When the button is pressed, a popup window should appear to confirm that the timer should be restarted. If restart is confirmed then the timer should be restarted, else the timer should remain as it was. You may have to pay attention to how this interacts with the ding sound (see comment by jbjarn17 below).

**Describe alternatives you've considered**
An alternative could be to simply remove the play/pause-button when the timer finishes.

**Prototypes**
See images or video demonstration in zip.
[RestartButtonPrototype.zip](https://github.com/aau-giraf/weekplanner/files/4316779/RestartButtonPrototype.zip)
![RestartButtonPrototype1](https://user-images.githubusercontent.com/55434874/76395196-0b4bda80-6377-11ea-9c65-90865670beec.png)
![RestartButtonPrototype2](https://user-images.githubusercontent.com/55434874/76395199-0be47100-6377-11ea-895a-2ad46340d1f4.png)

**Comment by jbjarn17** [comment]
I have noticed that after the ding sound has been attached to the timer(issue #264, pr #312) that the sound plays again if you push the play/pause button after the timer has finished.
