### ISSUE TITLE
Timer is still usable even when activity is cancelled.

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#309]
**Describe the bug**
When a guardian has cancelled an activity with a timer, both the guardian and citizen can use the timer despite the activity being cancelled.

**To Reproduce**
1. Go to an activity as a guardian, cancel activity, create timer.
2. Observe how timer is still fully usable.

**Expected behavior**
The timer buttons should not exist when a activity is cancelled.

**Actual behavior**
Timer can still be created and used after activity has been cancelled. Can also still be used when created before activity is cancelled.

**Screenshots**
No.

**Environment (please complete the following information):**
Observed on emulator and phone (Android).

**Comment by Nannanas** [comment]
Gaurdian view. Buttons for the timer is visible again if the "fortryd" button is clicked.
![Aktivitet_Cancelled_Timer_Alt1](https://user-images.githubusercontent.com/38284952/76603464-46801200-650d-11ea-87ed-889dcb4890ef.png)

Citizen view. Both when a timer is set or not.
![Aktivitet_Cancelled_citizen](https://user-images.githubusercontent.com/38284952/76608443-e5107100-6515-11ea-9154-c929650b835e.png)

**Comment by EsbenNedergaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disable the timer or remove it to fix #309 (timer problem)](https://trello.com/c/J0PQBtXK/5-disable-the-timer-or-remove-it-to-fix-309-timer-problem)

**Comment by EsbenNedergaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write Tests for #309 (timer problem)](https://trello.com/c/UnJhe3LI/6-write-tests-for-309-timer-problem)
