### ISSUE TITLE
Creating a new weekplan in the same week as an existing weekplan simply overwrites the existing weekplan

### ISSUE THREAD

**Issue by antonhpalmer** [aau-giraf/weekplanner-OLDUI#310]
**Describe the bug**
Imagine we are in week 11 and the user wants to create a weekplan for next week. The user creates a new weekplan but makes a typo, writing week 11 instead of 12 - now all information in the previous weekplan for week 11 is lost.

**To Reproduce**
1. Go to weekplan selector screen in Guardian mode
2. Take note of the week number and year of one of the existing weekplans
3. Click on 'Create new weekplan'
4. Input the same week number and year of the existing weekplan and press save
5. Observe that the weekplan for that particular week and year has been overwritten together with all the activities

**Expected behavior**
I can think of two options:
1. Popup window asking if you want to overwrite the existing weekplan
2. Do not allow overwriting - popup window saying that a weekplan already exists for that particular week and year
I will leave it to @aau-giraf/sw613f20 to choose the best option.

**Actual behavior**
Simply overwrites the existing weekplan for the particular week and year.

**Comment by Lortemanden** [comment]
I think that it is the PO group that should answer the question about expected behavior. And the PO group answers that option 1 sounds like the better option.

**Comment by EsbenNedergaard** [comment]
The same problem also happens, when you edit a weekplan to have the same week number and year as another week plan

**Comment by AAU-Phil** [comment]
![Prototype](https://user-images.githubusercontent.com/34337844/76608101-5f8cc100-6515-11ea-8e25-d620a4b09833.PNG)
Prototype for denne popup.
Med indsæt år og uge menes der at hente det år/uge man prøver at oprette en ugeplan it, som allerede har en.

**Comment by giano574** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix week plan overwrite (#310)](https://trello.com/c/Q0bN7kSQ/1-fix-week-plan-overwrite-310)
