### ISSUE TITLE
As a developer I would like the position of the weeks and days for the week overview not to be hardcoded 

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/weekplanner-OLDUI#315]
**Is your feature request related to a problem? Please describe.**
The position of the weeks and days for the overview is hardcoded, so it would have to be manually changed if the screen sizes change. 

**Describe the solution you'd like**
I would like flutter to automatically fix the position after the screen size. 

**Describe alternatives you've considered**
None

**Comment by T-Dawq** [comment]
Group 16 worked on this in 2020S0.
