### ISSUE TITLE
Text sizes are implemented differently throughout the app and are often inconsistent with the design guide in the wiki

### ISSUE THREAD

**Issue by jkrod** [aau-giraf/weekplanner-OLDUI#316]
**Is your feature request related to a problem? Please describe.**
Everywhere in the app font sizes are implemented differently and often hardcoded to different sizes. Furthermore bold font is used, where the design guide in the wiki mention that it shouldn't be used anywhere and the AutoSizeText widget is not used everywhere and instead the Text widget is used. The design guide mentions that AutoSizeText should be used.

To see examples of these different implementation, go to the different classes in the screens and widgets folders and check for style properties and uses of Text() and AutoTextSize widgets as child properties.

**Describe the solution you'd like**
I would like a consistent implementation of text sizes throughout the app without hardcoding in coherence with what is a agreed upon in the design guide and potentially dependent on the screen orientation (landscape/portrait). The AutoSizeText widget should always be used for dynamic display of text.

**Describe alternatives you've considered**
With regards to screen orientation, the OrientationBuilder or the MediaQuery.of(context).orientation could be considered. I believe in the widgets folder another approach to orientation have also been used, where the orientation is calculated in the _isTablet() method.

**Additional context**
This was discovered and is mentioned in issue #233 . Note that the design guide in the wiki mentions 20/30 pt for font sizes in portrait/landscape mode everywhere in the app. This has been discussed with the PO group and potentially demands a new issue because: On small devices, e.g. the supported mdpi of 600x1024 for screen sizes, these font sizes are not possible and still have weekdays appear on one line in the weekplanner (without using a scrollbar in the buttom). 

Potentially the approach to font sizes should be more dynamic with the minimum supported screen size and padding choices being the determining factor for minimum font sizes and maybe just have max font size.

**Comment by soenderby** [comment]
Related to aau-giraf/wiki#139

**Comment by Kaliahh** [comment]
Info needed: Is this actually a problem anymore?

**Comment by Kaliahh** [comment]
It definitely is a problem. The font sizes defined in font_sizes.dart are hardly used and need to be commented. We don't need an `activity_screen_buttons` that is size 23, and `medium` that is size 24, we just need the medium.
