### ISSUE TITLE
No error message when trying to copy or delete 0 activities 

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/weekplanner-OLDUI#317]
**Describe the bug**
There is no error message when trying to copy or delete 0 activities in a overview for a weekplan. 

**To Reproduce**
1. Go to a weekplan in the app
2. Click on edit in the top right corner
3. Click on delete or copy

**Expected behavior**
A clear and concise error message that no activities have been selected

**Actual behavior**
No error message

**Environment (please complete the following information):**
- OS: Android
- Emulator: PIxcel c
- Phone Android samsung galaxy s7

**Comment by EsbenNedergaard** [comment]
@aau-giraf/sw613f20 
After looking into the issue we discovered that another solution could be to disable the buttons, when zero activities have been selected. This is already done in other places in the application, so we would like to hear if this is an okay solution instead.
- The buttons have an isEnabled and isEnabledStream, an example can be seen in edit_weekplan_screen

![image](https://user-images.githubusercontent.com/33868248/76946275-14532380-6904-11ea-8204-e28a1ec2de5a.png)

**Comment by EsbenNedergaard** [comment]
Vi har også opdaget at samme fejl sker når man prøver at slette 0 **weekplans** skal vi oprette et nyt issue til dette.

**Comment by Lortemanden** [comment]
@EsbenNedergaard Der skal oprettes et ny issue for weekplans. Det lyder som en fin ide bare at disable knappen istedet.

**Comment by EsbenNedergaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write Tests for #317 (0 activities)](https://trello.com/c/JRkeoAnN/3-write-tests-for-317-0-activities)

**Comment by EsbenNedergaard** [comment]
We merged in https://github.com/aau-giraf/weekplanner/pull/343, however it does not seem to close the issue so i am closing it manually
