### ISSUE TITLE
As a guardian I would like a settings function so that i can edit the standard settings for a specific citizen

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#323]
**Is your feature request related to a problem? Please describe.**
It is important for the guardians to edit how a weekplan is shown to each individual citizen (e.g colors and number of days)

**Describe the solution you'd like**
A settings icon in the top right that gives acces to a settings menu as shown in the prototypes. The settings icon should becom available after a citizen has been selected. It is not part of the issue to add functionality to the buttons in the settings menu.

**Comment by Lortemanden** [comment]
Group 14 from issue #15  might have already done some work on this

**Comment by Nannanas** [comment]
Settings button added to the weekplans overview
![Weekplans_with_settings](https://user-images.githubusercontent.com/38284952/76605360-a4fabf80-6510-11ea-8d52-24657df31e7d.png)

Settings page, that appears when settings buttons is clicked.  This issues only concern is making the looks ready for the functionalities. This pages functionalities is to be implemented later, by other issues.
![citizen_settings](https://user-images.githubusercontent.com/38284952/76610114-b942ba80-6518-11ea-8385-9580bb3d7733.png)

**Comment by jrodel17** [comment]
**Relateret til api_client issue #23**

**Comment by jkrod** [comment]
**Related to api_client issue:** aau-giraf/api_client#23
