### ISSUE TITLE
As a previous PO I would like to not be auto assigned to issues so that I won't be spammed on my email

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#324]
Currently, the 2019 PO group is assigned every time someone makes a task creation request.

While we love to keep track of what you guys are doing with the app, it would be great to not be assigned issues on a weekly basis.

Thanks!

(This is for both the weekplanner repo and wiki repo, I haven't checked for the others.)

**Comment by mathiasandresen** [comment]
you should now be removed

**Comment by mathiasandresen** [comment]
was done in direct commit https://github.com/aau-giraf/weekplanner/commit/604f6f8973821f65a07a51efd5dec309788f3585
This could be done since its not related to the code base, but rather to github

**Comment by Tekrus** [comment]
This is still a problem in the following repositories:
- wiki 
- web-api repository 
- giraf-production-swarm (maybe? I know @thomaslhansen is still working on GIRAF, but not sure if the four people there are the ones that should auto assigned)

**Comment by mathiasandresen** [comment]
Ahh, my bad

**Comment by Tekrus** [comment]
This will be closed by:

https://github.com/aau-giraf/web-api/pull/59
https://github.com/aau-giraf/wiki/pull/141

I haven't updated the GIRAF production swarm, since @thomaslhansen is still on the project, so I figured he'll do it if they're no longer interested in being auto-assigned.
