### ISSUE TITLE
As a guardian I would like to be able to copy weekplans so that I can easily reuse weekplans

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#325]
**Describe the solution you'd like**
When the edit button is pressed a delete button is shown. A additional copy button should also pop up as shown in the picture below. Just as with the activities it should be possible to select more then one week. 
![image](https://user-images.githubusercontent.com/55434783/77523666-5f31e580-6e86-11ea-8709-980cfdd37caf.png)

When the copy weekplan button is pressed a popup as shown below should popup.
![image](https://user-images.githubusercontent.com/55434783/77523365-ea5eab80-6e85-11ea-8897-90b804321332.png)

If the "kopier til andre borgere" is pressed a screen with all the citizens as shown below should pop up. On this screen you can chose one or more citizens to copy the weeks too.  
![image](https://user-images.githubusercontent.com/55434783/77523492-19751d00-6e86-11ea-9839-83bc3867d993.png)

When the weeks have been copied, the following pop up should appear.
![image](https://user-images.githubusercontent.com/55434783/77523597-47f2f800-6e86-11ea-80db-74c180cda2f9.png)

If there already exist a weekplan with the same date as the one being copied in the destantion the following popup should appear. Where the ændr button should take you to the same screen as tilføj ugeplan with the information for the weekplan being copied.  
![image](https://user-images.githubusercontent.com/55434783/77541944-b8f5d800-6ea5-11ea-8fd3-b2580cc7275f.png)

**Comment by holyfailer** [comment]
![image](https://user-images.githubusercontent.com/55434839/79547382-1ab7f500-8094-11ea-87ac-817b027f5bce.png)
Her er et alternativt til hvordan det kan se ud når teksten fylder for meget i portrait mode

**Comment by T-Dawq** [comment]
Gruppe 12 arbejdede med dette i Sprint 2.
Funktionalitet er implementeret.
Der er PR med kommentarer, som der skal følges op på.
Mangler nogle tests.
Gruppe 12 vil gerne arbejde med dette i Sprint 3.
