### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by Jakobzs** [aau-giraf/weekplanner-OLDUI#327]
**Is your feature request related to a problem? Please describe.**
The purpose is to make it possible to test the application without having to compile the codebase yourself.

**Describe the solution you'd like**
I'd like for GitHub Actions to store the created artifacts of the generated APK (Android) and IPA (iOS) files upon certain events. Such an event could be a [Git Tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging), which could occur when a new sprint has been finished. Another event would be when merging to master has finished.

**Describe alternatives you've considered**
There are no "alternatives" for this.

**Additional context**

**Comment by Kaliahh** [comment]
The artifacts can be found under Actions\CI on GitHub
