### ISSUE TITLE
As a developer is would like a Visual Studio Code Workspace

### ISSUE THREAD

**Issue by Jakobzs** [aau-giraf/weekplanner-OLDUI#328]
**Is your feature request related to a problem? Please describe.**
I would like to have a Visual Studio Code workspace to make it simpler to open the project.

**Describe the solution you'd like**
I'd like for the Visual Studio Code workspace to be in the main directory of the repository. It should highlight the important parts of the repository, such as the "lib", "test", "ios", and "android" directories. Any file that has no importance to the project should be hidden.

"lib" could eventually be renamed to "Code" in the workspace.

If possible as well, perhaps make it so that the directory "ios" is only visible on OSX, although reading into this [issue](https://github.com/microsoft/vscode/issues/5595) it does not seem possible yet.

**Comment by nbhansen** [comment]
closed for deprecated
