### ISSUE TITLE
As a guardian i would like to have an admin page

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/weekplanner-OLDUI#332]
**Is your feature request related to a problem? Please describe.**
There is a admin page where the guardian should be able to log in via the web and manage the weekplanner for citizens. It can be found via this link  http://srv.giraf.cs.aau.dk/DEV/API/admin/login.html but it is not working.

**Describe the solution you'd like**
I would like the admin site to be up and running
**Describe alternatives you've considered**
None

**Additional context**
The admin panel can be found at web-api/GirafRest/wwwroot/admin/ and then main.html. Issue aau-giraf/web-api#51 is about the same but on the web-api

**Comment by nbhansen** [comment]
poorly described and deprecated
