### ISSUE TITLE
The delete weekplan button is not disabled when 0 weekplans are selected. 

### ISSUE THREAD

**Issue by EsbenNedergaard** [aau-giraf/weekplanner-OLDUI#338]
**Describe the bug**
The delete weekplan button is not disabled when you have selected zero week plans. 

**To Reproduce**
1. Go to the weekplan selector screen
2. Click on edit mode, and then click the **delete** button.
3. See error

**Expected behavior**
The button should be disabled by setting:
- isEnabled: false,
- isEnabledStream: to some value checking amount of marked week plans is greater than zero. 

**Actual behavior**
The button is still enabled and a pop-up appears that does not make much sense see picture. 

**Screenshots**
Example of the pop-up that is given when you click the button with 0 week plans selected.
![image](https://user-images.githubusercontent.com/33868248/76951761-76178b80-690c-11ea-8330-ba2877ee946e.png)

**Environment:**
OS: Android
Emulator: PIxcel c

**Comment by Lortemanden** [comment]
This has been fixed by making a different popup
