### ISSUE TITLE
Edit linter to accept up to 120 characters

### ISSUE THREAD

**Issue by christianhurley** [aau-giraf/weekplanner-OLDUI#345]
It was decided within the developer team that the linter should accept 120 characters

To fix it, edit the linter

**Comment by mathiasandresen** [comment]
Seems it cannot be be changed at the moment, since the rule is hardcoded to 80.
https://dart-lang.github.io/linter/lints/lines_longer_than_80_chars.html

**Comment by Lortemanden** [comment]
Since this cant be fixed it's closed!!!!
