### ISSUE TITLE
Timer is not saved when you cancel activity and then undo the cancel

### ISSUE THREAD

**Issue by EsbenNedergaard** [aau-giraf/weekplanner-OLDUI#352]
**Describe the bug**
When you add a timer to the activity and then cancel the activity imediatly after, however you regret that and undo the cancelation then the timer still seems to be there just fine, however if you leave the activity and go back into it your timer is now gone. 

**To Reproduce**
1. Go into any activity in the weekplan screen
2. Click on the add timer button and add a new timer for an example for 5 seconds
3. Click the "Aflys" button
4. Click the "Fotryd" button
5. Leave your activity
6. Enter back into the activity, and see that your timer is now gone.

**Expected behavior**
I expected the timer to not get deleted when i undo my cancelling of an activity. 

**Actual behavior**
The timer is some how deleted when you cancel then undo the cancelleation, the problem seems to be something with the undo button because if you cancel then undo an activity and then leave the activity you can sometimes for a short second see the red cross on the activity still.

**Comment by Lortemanden** [comment]
Group 8 has worked with this in sprint 2.
They have looked at the problem but found the problem was in the web-api and made a issue in the api, but it might be a duplicate. 
No group should be assigned to this issue since it will be solved by doing issue aau-giraf/web-api#98
