### ISSUE TITLE
Pictures/icons is not implemented for citizens

### ISSUE THREAD

**Issue by jbjarn17** [aau-giraf/weekplanner-OLDUI#362]
**Is your feature request related to a problem? Please describe.**
I was working on issue #66 and I didn't seem to be able to upload a picture/icon for a new citizen. The API is not fully implemented to support this feature.
There is however a TODO in the user_api.dart...

**Describe the solution you'd like**
To create a new user, the register method in account_api is used. This could be the place to implement this. Or maybe give the user the ability to choose a mock image until one has been uploaded.

**Describe alternatives you've considered**
Right now there is a TODO in the user_api that seems to be regarding this issue, but I'm not sure.

**Additional context**
Screenshot from the client_api -> user_api.dart
<img width="303" alt="user_api_icon" src="https://user-images.githubusercontent.com/34233264/77999440-f8ec0d80-7332-11ea-93a5-5130300bc23f.PNG">

**Comment by Kaliahh** [comment]
#155 should be implemented as well

**Comment by dkalaxdk** [comment]
Same as aau-giraf/api_client#3
