### ISSUE TITLE
The app uses username instead of display name

### ISSUE THREAD

**Issue by jbjarn17** [aau-giraf/weekplanner-OLDUI#363]
**Describe the bug**
When a citizens name has to be displayed in the app, the username is displayed instead of the display name. The display name is not required when creating a new user, which might be the problem.

**To Reproduce**
1. Setup a local database
2. Make sure you set the weekplaner to use this database
3. Make sure the feature described in issue #66 is implemented
4. Use this new feature to create a new citizen
4.1. Display name and username should be noticeable different
5. Find the new user and see which name is used in the app

**Expected behavior**
When a users name is displayed I expect the app to use the display name

**Actual behavior**
The app uses the username when the display name should be used

**Screenshots**
<img width="961" alt="createCitizen" src="https://user-images.githubusercontent.com/34233264/78012323-13c77d80-7345-11ea-890e-805ec5b709bc.PNG">
<img width="961" alt="createCitizen_weekplan" src="https://user-images.githubusercontent.com/34233264/78012339-175b0480-7345-11ea-8e29-e76e4a9a19c3.PNG">

**Environment (please complete the following information):**
- OS: Android
- Emulator: Tested on emulator
- Phone/Tablet: Nexus 7
- APK Version [e.g. 22]

**Additional context**

**Comment by T-Hauge** [comment]
In solving this issues we also made the use of displayName consistent, since we inconsistently used both displayName and screenName for it.
