### ISSUE TITLE
Warning on memory waste/security issue for API lvl 19

### ISSUE THREAD

**Issue by jkrod** [aau-giraf/weekplanner-OLDUI#364]
**Describe the bug**
When running the weekplanner app using API level 19, I get the following warning:

> Running Gradle task 'assembleDebug'...
> √ Built build\app\outputs\apk\debug\app-debug.apk.
> **WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk.** Please fix.
> 
> Installing build\app\outputs\apk\app.apk...

**To Reproduce**
1. Create an emulator of API level 19
2. Start it
3. Build the application
4. See warning in output console

**Expected behavior**
No warning

**Actual behavior**
A warning.

**Environment (please complete the following information):**
- OS: Android
- Emulator: Nexus 7
- APK Version: 19

**Comment by Lortemanden** [comment]
Is this happening cause the API level 19 is a outdated API level?
