### ISSUE TITLE
Overflow and multiple lines while copying activities on smaller device

### ISSUE THREAD

**Issue by Laexander** [aau-giraf/weekplanner-OLDUI#366]
**Describe the bug**
When on a smaller device, the edit mode used to mark activities has several overflows. When entering edit mode, when tapping the copy button, the name of the weekdays are all split over 2 lines in portrait mode, while in landscape the cancel and copy buttons are overflowed.

**To Reproduce**
Steps to reproduce the behavior (do in both landscape and portrait mode):
1. Go to 'Weekplanner screen'
2. Click on 'Edit mode'.
3. Select a activity.
4. Press the "kopier" button
5. See error

**Expected behavior**
No overflow (landscape) and readable weekday names (portrait).

**Actual behavior**
Overflow (landscape) and difficult to read weekdays(portrait).

**Screenshots**
Week names on multiple lines in portrait
![KopierActivityBad](https://user-images.githubusercontent.com/17495079/78024486-bccba380-7358-11ea-8e8a-735501dcf19a.jpg)

Overflow for "fortryd" and "kopier" buttons in landscape
![KopierActivityLandscapeBad](https://user-images.githubusercontent.com/17495079/78024548-d8cf4500-7358-11ea-8c79-fe8692aa583c.jpg)

**Environment (please complete the following information):**
- OS: Android
- Emulator
- Resolution 600x1024
- APK Version

**Additional context**
Found while doing pre-release testing for https://github.com/aau-giraf/weekplanner/issues/255

**Comment by Lortemanden** [comment]
We have also looked at this issue and ours works fine for the 600x1024 resolution?
![image](https://user-images.githubusercontent.com/55434783/78025328-25ffe680-735a-11ea-81c1-ca81fd819e4b.png)

**Comment by Laexander** [comment]
Not a problem after closer inspection, there were problems with the device tested on rather than problems with the application
