### ISSUE TITLE
Pressing the back button when in edit mode of a citizen results in bugs in the edit mode

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/weekplanner-OLDUI#369]
**Describe the bug**
When a guardian is in edit mode and presses the back button (Top Left), the state of the edit mode bar is hard to understand.

**To Reproduce**
1. Select a citizen
2. Click on 'Edit'
3. Mark 1 week
4. Press the back button (Top Left)
5. Select a citizen
6. Observe that no week is selected
7. Press edit

**Expected behavior**
To be unable to press the edit button in step 7.

**Actual behavior**
Able to press the edit button with the input from step 3.

**Environment (please complete the following information):**
- Emulator?

**Video**
https://streamable.com/7dwux

**Additional context**
In the video above, I also tested what would happen if I selected multiple images. The state seems to handle this badly, giving me an Edit button which does not work.

**Comment by Lortemanden** [comment]
Might be fixed by #367
