### ISSUE TITLE
As a guardian i would like to resume multiple canceled activities in the weekplan edit screen

### ISSUE THREAD

**Issue by dtidemann** [aau-giraf/weekplanner-OLDUI#371]
**Is your feature request related to a problem? Please describe.**
When in the weekplan edit screen it is possible to cancel multiple activities but not resume them again, this has to be done individually.

![unknown](https://user-images.githubusercontent.com/31842043/78118299-1a1e2e00-7407-11ea-8b2a-ea24aeabc8c8.png)

**Describe the solution you'd like**
A button to resume multiple activities.

**Describe alternatives you've considered**
When clicking the cancel button on canceled activities, they could be resumed.

**Additional context**
It is also possible to cancel already canceled activities, without anything happening.

**Comment by T-Dawq** [comment]
To be discussed with the customers.

**Comment by soenderby** [comment]
There should be a button that, when pressed resumes the currently selected activities. If some of the selected activities are not canceled, the button should not change these.   

Multiple canceled activities can be selected.
![2020e_2_1_GUA_WP371 Resuming canceled tasks](https://user-images.githubusercontent.com/33911621/94662760-1cefd200-0309-11eb-9608-480eba370678.png)  
  
These activities should no longer be canceled after the "Genoptag" button has been pressed.
![2020e_2_2_GUA_WP371 Resuming canceled tasks result](https://user-images.githubusercontent.com/33911621/94662763-1eb99580-0309-11eb-8f2b-b3d6e1b8ac51.png)
