### ISSUE TITLE
As a guardian i would like "instillinger" to shown the chosen setting so that i know what setting has been chosen.

### ISSUE THREAD

**Issue by holyfailer** [aau-giraf/weekplanner-OLDUI#376]
**Describe the solution you'd like**
Under "instillinger"(the little cog, top right) at the weekplanner overview, it would be nice to actually seen what settings that has been chosen. 
In addition it would be nice when you chose a setting (eks. "vis kun i dag") it automatically jump back to  the menu. 

**Describe alternatives you've considered**
None

**Additional context**
![3](https://user-images.githubusercontent.com/55434839/78241162-448fea00-74e0-11ea-9dfe-6616ddb411c3.PNG)

**Comment by jkrod** [comment]
**_Comment for future reference:_**

After clarifying with the PO group, the screenshot above is a prototype and how it should look, as of now, not all the settings are implemented, so specifically the task is about making it show the setting for "Antal Dage" as above it is show to currently have the setting "Mandag til fredag"

Furthermore the route to number_of_days_selection_screen, should be pop'ed after making a choice.
