### ISSUE TITLE
As a citizen my information should be deleted when its is no longer needed

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/weekplanner-OLDUI#379]
**Is your feature request related to a problem? Please describe.**
The information in the GIRAF system is never deleted which is against the GDPR law. 

**Describe the solution you'd like**
The information for a guardian or citizen should automatically be deleted when it's no longer needed. This is when the guardian or citizen is removed from the system. Other reasons can be found from issue aau-giraf/wiki#170. It might also be related to the form from issue #378

**Comment by nbhansen** [comment]
beware that we need a way of handling if a trustee or guardian is deleted but not the citizen, or vice versa
