### ISSUE TITLE
As a developer i would like the app to be deployed to Google Play when it is merged into master

### ISSUE THREAD

**Issue by mathiasandresen** [aau-giraf/weekplanner-OLDUI#384]
**Is your feature request related to a problem? Please describe.**
The app is not deployed to the play store when a release is merged into master

**Describe the solution you'd like**
For a GitHub Actions workflow to do it.

**Describe alternatives you've considered**
Manual upload

**Additional context**

**Comment by soenderby** [comment]
This has been implemented
