### ISSUE TITLE
As a developer I need code infrastructure for a local database and model adapters in order to implement offline functionality

### ISSUE THREAD

**Issue by christianhurley** [aau-giraf/weekplanner-OLDUI#389]
**Is your feature request related to a problem? Please describe.**
An Infrastructure to be able to use local database in offline mode needs to be implemented in order to further develop on the offline implementation.
Link to offline issue: https://github.com/aau-giraf/weekplanner/issues/9

**Describe the solution you'd like**
Suggenstion https://github.com/aau-giraf/wiki/blob/wiki_issue_155/docs/development/Offline_mode.md

**Describe alternatives you've considered**
SQLite (sqflite til flutter) could be used for the local database

**Comment by mathiasandresen** [comment]
This is the base for all offline functionality, and should be developed carefully.

**Comment by tdybda17** [comment]
This issue can be closed due to https://github.com/aau-giraf/api_client/pull/51

**Comment by T-Dawq** [comment]
Gruppe 14 arbejdede med dette i Sprint 2.
Der blev fundet en bug relateret til issuet: https://github.com/aau-giraf/api_client/issues/52
De vil helst ikke arbejde som hovedgruppe på issuet i Sprint 3, men de vil gerne arbejde som bigruppe sammen med en anden gruppe.
