### ISSUE TITLE
As a guardian I would like to have access to x number of pictograms in offline mode using the local database.

### ISSUE THREAD

**Issue by Nannanas** [aau-giraf/weekplanner-OLDUI#396]
**Is your feature request related to a problem? Please describe.**
This issue is related to the overall implementation of offline functionality.
Link: #9 

**Describe the solution you'd like**
Decide which pictograms that should be saved in the local database.
The x pictogram should be the pictograms that is already is used in the weekplans for the citizens the guardian has access to.

**Comment by Kaliahh** [comment]
Replaced by #632
