### ISSUE TITLE
As a guardian, I would like to be able to mark activity(s).

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#4]
I would like to mark one or more activities, which enables the option to delete/copy/move all of them at the same time.

**Comment by jenspetur94** [comment]
**Prototyper**

![image](https://user-images.githubusercontent.com/22811843/53232856-502da200-368c-11e9-9cb7-e39cca1a94d6.png)

![image](https://user-images.githubusercontent.com/22811843/53232876-5ae83700-368c-11e9-8386-72c4bdebf583.png)

![image](https://user-images.githubusercontent.com/22811843/53232895-650a3580-368c-11e9-9986-39013eab7e00.png)

**Comment by andpaacoke** [comment]
I would like a button/icon to enter mark mode, with the opportunity to complete, copy or delete the marked activities
![image](https://user-images.githubusercontent.com/22811754/53301501-e233d700-3853-11e9-8d56-a913bba3f79f.png)

**Comment by Alechj** [comment]
- [x] Add edit button

- [ ] Enable selection across panels

- [ ] Obtain ID of each pictogram

- [ ] Implement functionality which supports simultanous edits to several pictograms

**Comment by andpaacoke** [comment]
Duplicate of #59
