### ISSUE TITLE
As a guardian i would like the weekplans for a citizen to be separated by upcoming and old 

### ISSUE THREAD

**Issue by AAU-Phil** [aau-giraf/weekplanner-OLDUI#416]
**Describe the solution you'd like**
The past weekplans should be saved below the upcoming weekplans, and they should be grayed out to represent them being old weekplans. They should also be accessible as to allow for copying into a week in the future. 

**Describe alternatives you've considered**
Having them at the bottom of a long list of all weekplans, after the incompleted weekplans

**Additional context**
![2020f_7_A_GUA_WP416](https://user-images.githubusercontent.com/55434874/81814621-4a3e0e00-9529-11ea-9a2a-5a0578fd401d.png)

**Comment by T-Dawq** [comment]
Gruppe 12 arbejdede med dette i Sprint 2.
Stort set alt funktionalitet er implementeret.
Mangler nogle tests.
Gruppe 12 vil gerne arbejde med dette i Sprint 3.
