### ISSUE TITLE
As a guardian i would like to be able to search for a specific weekplan so it is easier for me to find

### ISSUE THREAD

**Issue by AAU-Phil** [aau-giraf/weekplanner-OLDUI#418]
**Describe the solution you'd like**
It should be possible to search for week plans by name, week, and/or year. Any week plan that does not match the search criteria should disappear, while still maintaining its normal sorting. 

**Additional context**
The solution should look like this:

**A search button should be added to the top bar.**
![2020e_10_GUA_1_WP418 Expanded search bar](https://user-images.githubusercontent.com/42242841/98003953-a35b7000-1def-11eb-967a-344bb36410be.png)

**After pressing the search button, a search bar should appear:**
![2020e_10_GUA_2_WP418 Expanded search bar](https://user-images.githubusercontent.com/42242841/98004114-d30a7800-1def-11eb-8f40-545c18f32b0c.png)

**The user should then be able to type in the name, week, and/or year and get the resulting week plans:**
![2020e_10_GUA_3_WP418 Expanded search bar](https://user-images.githubusercontent.com/42242841/98004241-f9301800-1def-11eb-8016-7814acaf44a6.png)

**The user can also choose to filter their search. As an example, removing the week number criteria reveals a week plan that is not in week 4:**
![2020e_10_GUA_4_WP418 Expanded search bar](https://user-images.githubusercontent.com/42242841/98004404-2ed50100-1df0-11eb-89d9-c9e4d62350aa.png)

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 418](https://trello.com/c/GoblJxa1/24-issue-418)

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 418](https://trello.com/c/2jfG93ue/58-issue-418)
