### ISSUE TITLE
The activities jumps up and down

### ISSUE THREAD

**Issue by Simon97** [aau-giraf/weekplanner-OLDUI#419]
[video_of_bug.zip](https://github.com/aau-giraf/weekplanner/files/4481823/video_of_bug.zip)
**Describe the bug**
Please watch the video.
The activities are not moving as expected when scrolling in citizen mode, watching only one day and having a lot of activities on the current day

**To Reproduce**
1. Go to weekplan selection screen
2. Go to settings and set 'Antal dage' to 'vis kun i dag'
3. Select a weekplan which has at least 10 activities (unsure about the amount, but you should be able to scroll)
4. Switch to citizen mode
5. Try to scroll to the button and up again.

**Expected behavior**
The activities should move up and down corresponding to your finger

**Actual behavior**
It is hard to scroll to the top activity again after scrolling down.
**Environment (please complete the following information):**
- OS: [Android]
- Phone [Huawei P30, Huawei P20 lite and Sony tablet]
- APK Version [Pas]

**Comment by Lortemanden** [comment]
Group 9 has worked with this in sprint 2.
Der mangler et review, men den er færdig.
Group 9 would like to work with this in sprint 3.
