### ISSUE TITLE
Periodic errors in asynchronous tests

### ISSUE THREAD

**Issue by Semicolon1071** [aau-giraf/weekplanner-OLDUI#425]
**Describe the bug**
Periodic errors occur while testing `test/blocs/timer_bloc_test.dart`, and it seems to be related to the asynchronous nature of the tests.

**To Reproduce**
1. Open a command-line shell and go to the root folder of the weekplanner project.
2. Execute `flutter test` repeatedly in Weekplanner repository, until an error occur (might require > 75 iterations, see attached scripts for automation) 
3. See error

**Expected behavior**
The expected behavior would be that all tests passes, no matter how many times they are executed.

**Actual behavior**
The actual behavior is currently that errors occur once in a while (varies between environments). I experienced issues around 1-2 times per 100 runs of `flutter test`.

**Screenshots**

**Environment (please complete the following information):**
- OS (test platform): Windows 10, Ubuntu 18.04
- Emulator: Not applicable.
- Phone [e.g. Iphone X, Pixel 2]: Not applicable.
- APK Version [e.g. 22]: Not applicable.

**Additional context**
Flutter version: 1.12.13+hotfix.9 (channel: stable)
Dart version: 2.7.2

**Automation of flutter tests**
To avoid having to manually execute the `flutter test` command until an error occurs, the attached .zip file contain two .sh scripts which automates this process. The scripts are very simple, and might require modifications, such as providing more elaborate output, to be more useful in discovering the nature of the error(s). To execute them, the full path to the local Weekplanner repository is required as a parameter, such as: `./repeat_flutter_tests_and_stop_upon_error.sh C:/Users/Andreas/repo/weekplanner`

[flutter_test_automation.zip](https://github.com/aau-giraf/weekplanner/files/4509111/flutter_test_automation.zip)

**Comment by Mustafa-ALD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 425](https://trello.com/c/yoyffPDe/23-issue)

**Comment by Mustafa-ALD** [comment]
**No issue found**
After following the guidelines we have not been able to reproduce the error.
And we have run the test 200 times without getting any errors.
