### ISSUE TITLE
As a guardian I would like to be able to view a given citizens week plan so that I can get an overview of what is happening this week for them

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#43]
Tasks:
- [x]     Make the BLoC needed (Reuse as much as possible)
- [x]     Make the UI reactive (i.e. show the relevant data)
- [x]     Make sure the UI upholds the settings set for the user (color, and so on)

**Comment by sipman** [comment]
THIS FEATURE IS "CONFLICTING" WITH #44 

This features UI is somewhat implemented, there might be a need to fix some small things. Therefore the main task here could be:

- Make the BLoC needed (Reuse as much as possible)
- Make the UI reactive (i.e. show the relevant data)
- Make sure the UI upholds the settings set for the user (color, and so on)
