### ISSUE TITLE
When creating a new citizen after another citizen has been created, error messages displays

### ISSUE THREAD

**Issue by jbjarn17** [aau-giraf/weekplanner-OLDUI#436]
**Describe the bug**
When creating a new user after another user has been created, error messages display in the text fields.

**To Reproduce**
1. Go to choose citizen screen.
2. Add new citizen.
3. When completed and you are returned to the choose_citizen_screen, press add new citizen again.

Now you should see error messages to each text field.

**Expected behavior**
When you try to create the second citizen, the fields should not display error messages

**Actual behavior**
When you try to create a second citizen, errors appear as if the info in the fields is not valid.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/34233264/80222858-bbd01e00-8647-11ea-8e9d-a6221991967f.png)

**Comment by Lortemanden** [comment]
We cannot recreate this bug. Can you recreate it?

**Comment by T-Hauge** [comment]
> We cannot recreate this bug. Can you recreate it?

No

However, group 12 in PR https://github.com/aau-giraf/weekplanner/issues/457 have solved issue https://github.com/aau-giraf/weekplanner/issues/453 which might be caused by the same problem. Therefore, they might solved this issue when solving the other.
