### ISSUE TITLE
Lines appear around completed activities in citizen mode

### ISSUE THREAD

**Issue by melanieselman** [aau-giraf/weekplanner-OLDUI#439]
**Describe the bug**
The lines around the completed actitivies are not removed when using the "Fjern aktiviteten for borgeren" setting together with the "Vis kun en dag",  "Mandag til fredag" or "Mandag til søndag" setting on iOS.

**To Reproduce**
1. Go to settings in the week plan selector screen. 
2. Click on "Tegn for udførelse" and select "Fjern aktiviteten for borgeren".
3. Click on "Antal dage" and select "Mandag til søndag" or "Mandag til fredag".
4. Go back and select a week plan.
5. Enter citizen mode.
6. Complete activities if there are not any.
7. See the lines that appear around the completed activity.

**Expected behavior**
No lines can be seen around completed activities when the "Fjern aktiviteten for borgeren" setting is selected. 

**Actual behavior**
Lines appear around the completed activity in citizen mode when the mentioned settings are chosen. Sometimes it varies depending on which iPad you use. On some iPads, some of the settings work, but not the other.

**Screenshots**

The lines can be seen below:

![image](https://user-images.githubusercontent.com/31991823/80370789-1e682a80-8891-11ea-86ea-6bb265541458.png)

How it is supposed to look: 

![image](https://user-images.githubusercontent.com/31991823/80370897-4bb4d880-8891-11ea-95e0-1519d1688a06.png)

**Environment (please complete the following information):**
- OS:  iOS
- Emulator: iPad Pro 12.9",  iPad Pro 9.7" and iPad Air 12.9".

**Comment by ProgDaniel** [comment]
After 2 attempts of testing on different systems (2 iPads; 1 physical and 1 emulator + 2 android emulators), the issue could not be replicated, and no white lines/boxes appeared on the screen in various circumstances. Therefore the issue seems to have been either a specific version issue or have been indirectly fixed through other pull requests.
