### ISSUE TITLE
As a citizen I would like to be able to view my week plan so that I know what is going to happen

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#44]
Tasks:
- [x]     Make the BLoC needed (Reuse as much as possible)
- [x]     Make the UI reactive (i.e. show the relevant data)
- [ ]     Make sure the UI upholds the settings set for the user (color, and so on)
- [ ]     Place a "switch to Citizen" icon and implement the functionality in a BLoC
- [ ]     Ensure that the Weekplan-Screen acts correctly when activating the Citizen mode

**Comment by sipman** [comment]
This features UI is somewhat implemented, there might be a need to fix some small things. Therefore the main task here could be: 
- Make the BLoC needed (Reuse as much as possible)
- Make the UI reactive (i.e. show the relevant data)
- Make sure the UI upholds the settings set for the user (color, and so on)
- Place a "switch to Citizen" icon and implement the functionality in a BLoC
- Ensure that the Weekplan-Screen acts correctly when activating the Citizen mode

**Comment by sipman** [comment]
This feature "Conflicts" with #43
