### ISSUE TITLE
Marking an activity with a timer as complete and then unmark it causes the activity to be deleted. 

### ISSUE THREAD

**Issue by tuanvu29** [aau-giraf/weekplanner-OLDUI#444]
**Describe the bug**
When you are in an activity with a timer and you mark the activity as completed and uncheck it again. The activity will then dissapear/be deleted from the weekplan screen.

**To Reproduce**
1. Go to an activity with a timer in citizen mode .
2. Mark the activity completed.
3. Then unmark the activity.
4. Go back to the weekplan screen and see the activity is gone.

**Expected behavior**
You should be able to mark and unmark an activity with a timer completed as many times as you would like.

**Actual behavior**
Deletes an activity with a timer when:
Marking it completed and then unmarking it.
or
Unmarking a completed activity and then marking it completed again.

**Screenshots**

**Environment (please complete the following information):**
- Emulator?
- Phone [e.g. Iphone X, Pixel 2]
- APK Version [e.g. 22]

**Additional context**

**Comment by Rsvend17** [comment]
Should be noted, that this issue would also appear, if you do this in guardian mode and reproduce the same steps, but with the cancel button.

**Comment by dkalaxdk** [comment]
Fixed via web-api#112
