### ISSUE TITLE
Unknown theme colors shown in user settings

### ISSUE THREAD

**Issue by Laexander** [aau-giraf/weekplanner-OLDUI#448]
**Describe the bug**
When looking at a user's settings, the weekplan themes sometimes shows a color not available in the settings

**To Reproduce**
This has been done using the local database from available in the web-api repository
1. Go to Choose citizen screen
2. Click on the user Deck
3. Click on the settings
4. See that the weekplanner themes is white and red
5. Click the 'farver på ugeplan' button
6. See that there is no white and red theme

**Expected behavior**
In the settings screen, it should show one of the available color themes.

**Actual behavior**
It shows an unknown color theme

**Screenshots**
Unknown color theme
![image](https://user-images.githubusercontent.com/17495079/80589514-9e6dcc00-8a1a-11ea-816e-a6ef8d685715.png)

Available color themes
![image](https://user-images.githubusercontent.com/17495079/80589539-a9c0f780-8a1a-11ea-8411-3e4cae148c0c.png)

**Environment (please complete the following information):**
- Android emulator : Pixel C 
- API 29
- Done using the local database and server from web-api repository

**Additional context**

**Comment by Lortemanden** [comment]
It should be noted that it's also not possible to see what theme is chosen after you click "farver på ugeplan"

**Comment by Laexander** [comment]
After the AUU server were running correctly, I went to check if there was an equivalent situation there, but could not find a citizen with unknown weekplan colors

**Comment by EsbenNedergaard** [comment]
I think that the reason for this weird color theme is that on the local database created when you write dotnet run --sample-data you get some users with some weird color theme values, which are different from the ones we defined.

**Comment by Laexander** [comment]
After further investigation, it seems the sample data for `weekdaycolors` table on web-api is wrong. 
Which causes the unknown week colors to appear.

**Comment by EsbenNedergaard** [comment]
This is not a bug, but just the sample data
