### ISSUE TITLE
As a citizen I would like to view details about the currently ongoing activity (such as time left and only the associated pictogram) so that I know what is happening and how long is left

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#45]
Tasks:

- [x] Make a view that shows the pictogram for the current activity
- [x] Show the timer (if one is assigned) with how long is left
- [x] Make a back button in the top bar to return to week plan

This is blocking #75

**Comment by LukasRH** [comment]
Closed with #143
