### ISSUE TITLE
Can not change the theme color for a weekplan under "Farver på ugeplan"

### ISSUE THREAD

**Issue by tuanvu29** [aau-giraf/weekplanner-OLDUI#451]
**Describe the bug**
Can not change the theme color for a weekplan under "Farver på ugeplan"

**To Reproduce**
1. Go to settings
2. Click on '.Farver på ugeplan'
3. click on any of the tabs
4. Nothing happens

**Expected behavior**
should change the theme

**Actual behavior**
nothing happen when tapping.

**Screenshots**

**Environment (please complete the following information):**
- Emulator?
- Phone [e.g. Iphone X, Pixel 2]
- APK Version [e.g. 22]

**Additional context**

**Comment by giano574** [comment]
Duplicate
