### ISSUE TITLE
Timers on activities are deleted when adding a new activity

### ISSUE THREAD

**Issue by Laexander** [aau-giraf/weekplanner-OLDUI#452]
**Describe the bug**
When adding a new activity on a week plan, timers on other activities are deleted

**To Reproduce**
1. Go to a weekplan
2. Add a activity with a timer (current state of timer is not important)
3. Then add a new activity 
4. Timer on previous activity is deleted

**Expected behavior**
Timer should still be there, whether it is running or not

**Actual behavior**
Timer has been deleted

**Screenshots**

**Environment (please complete the following information):**
Android emulator : Pixel C
API 29 & 19

**Additional context**
This seems to be the exact same problem from issue #413

**Comment by giano574** [comment]
Not a new issue:
https://github.com/aau-giraf/web-api/pull/98

**Comment by jkrod** [comment]
@giano574 Skal den ikke blot lukkes når den er linket og markeret som duplicate?
