### ISSUE TITLE
As a guardian i would like to have some text/box showing if i am missing some input when creating a new week

### ISSUE THREAD

**Issue by Rsvend17** [aau-giraf/weekplanner-OLDUI#453]
**Describe the bug**
When creating a new weekplan as a guardian, red text indicating that you are missing some inputs are only shown sometimes when you click "gem ugeplan". 

**To Reproduce**
1. Go to 'Opret ugeplan' screen
2. Click on 'Gem ugeplan' with no input.
3. See error.

**Expected behavior**
It should always indicate what is missing when clicking gem ugeplan, if something is missing.
This should also be the case with the image field.

**Actual behavior**
only sometimes show a red text indicating something is missing if a text box has been activated

**Screenshots**
The first two screenshots show that there is no indication to the user, that a field is empty. 
Last screenshot shows if a field has been activated with some text, and it is inputted wrong. Then it is shown correct. This does not come up when clicking on "gem ugeplan", only when you have entered the field once.
![Screenshot_1588159241](https://user-images.githubusercontent.com/34129384/80593144-eee82800-8a20-11ea-902d-e71467eda128.png)
![Screenshot_1588159097](https://user-images.githubusercontent.com/34129384/80593154-f3144580-8a20-11ea-8d46-b705bf0af220.png)
![Screenshot_1588158991](https://user-images.githubusercontent.com/34129384/80593159-f5769f80-8a20-11ea-858c-24256175fd41.png)

**Comment by T-Hauge** [comment]
This issue have been fixed, but was accidently overwritten by PR https://github.com/aau-giraf/weekplanner/pull/484.

**Comment by T-Hauge** [comment]
Obs. this is the wrong issue, and are therefore closed.
Its the issue https://github.com/aau-giraf/weekplanner/issues/459, that is accidently overwritten.
