### ISSUE TITLE
Wrong order of colors in weekplanner for standard theme color in citizen mode

### ISSUE THREAD

**Issue by tuanvu29** [aau-giraf/weekplanner-OLDUI#454]
**Describe the bug**
The colors of the days is in reverse order in citenzen mode for standard theme

**To Reproduce**
1. Go to an citizen that has the standard colors for theme.
2. Click on weekplanner of that citizen.
3. Then switch to citizen mode.
4. Color of the days is in reverse order.

**Expected behavior**

![image](https://user-images.githubusercontent.com/54982115/80594033-8b5efa00-8a22-11ea-9a31-e3dcfade2928.png)

**Actual behavior**

![image](https://user-images.githubusercontent.com/54982115/80594041-9154db00-8a22-11ea-8417-77ed97ebd609.png)

**Screenshots**

**Environment (please complete the following information):**
- Emulator?
- Phone [e.g. Iphone X, Pixel 2]
- APK Version [e.g. 22]

**Additional context**

**Comment by Lortemanden** [comment]
This is not the case on mine?
