### ISSUE TITLE
User has blue/white theme when logging in even though another setting has been chosen

### ISSUE THREAD

**Issue by MrPekar98** [aau-giraf/weekplanner-OLDUI#456]
**Describe the bug**
The stream _settings_ in _SettingsBloc_ has value _null_ when loading settings in _weekplan_screen.dart_. The blue/white theme has been chosen as the theme for the user when logging in before the theme setting is changed.

**To Reproduce**
1. Go to user settings and choose a theme other than the blue/white theme.
2. Logout and back in.
3. Go to a week plan in citizen mode.
4. See that the week plan has the blue/white theme.

**Expected behavior**
The user has the same theme as the user had when the user logged out the last time.

**Actual behavior**
User always has the blue/white theme in the week plan in citizen mode until the theme setting is changed.

**Additional context**
See method __buildActivityStateIcon()_ in weekplan_screen().

**Comment by aerlingsson** [comment]
Cannot reproduce. When clicking on other themes in settings nothing happens at all and blue/white theme is not the default.

**Comment by MrPekar98** [comment]
Someone have already created a PR that solves the issue in the theme settings. I suggest you try to reproduce the problem again when the PR has been merged.

**Comment by mathiasandresen** [comment]
@MrPekar98 
> 
> 
> Someone have already created a PR that solves the issue in the theme settings. I suggest you try to reproduce the problem again when the PR has been merged.

what PR?

**Comment by MrPekar98** [comment]
https://github.com/aau-giraf/weekplanner/pull/455

**Comment by aerlingsson** [comment]
Seems to have been fixed by https://github.com/aau-giraf/weekplanner/pull/455
