### ISSUE TITLE
As a guardian i would like to have some text/box showing if i am missing some input when creating a citizen

### ISSUE THREAD

**Issue by Rsvend17** [aau-giraf/weekplanner-OLDUI#459]
**Describe the bug**
When creating a new citizen as a guardian, red text indicating that you are missing some input are only shown when a field has been activated with some text, but not when you click on "Gem borger" button.

This is the same type of bug as : https://github.com/aau-giraf/weekplanner/issues/453

**To Reproduce**
1. Go to 'ny burger screen'
2. Click on 'Gem borger'
3. See error

**Expected behavior**
It should always indicate what is missing when clicking "Gem Borger", if something is missing and not just when you are editing the input field.

**Actual behavior**
Only sometimes show a red text indicating something is missing if a text field has been activated

**Screenshots**
First picture shows, if you have inputted into a field and click the "Gem Borger" It does not give any red box indication that a field is missing some input. 
Second shows that if the same field input is deleted a field is shown with red text. But when clicking "Gem Borger" in this state, it still does not show that the other fields are missing. 
Last screenshot is just a click on "Gem Borger" when no field have been activated, then no red text is shown. 
![Screenshot_1588162249](https://user-images.githubusercontent.com/34129384/80594496-63bc6180-8a23-11ea-91e5-3b973586e54d.png)
![Screenshot_1588162239](https://user-images.githubusercontent.com/34129384/80594501-67e87f00-8a23-11ea-8b42-58325c9827e7.png)
![Screenshot_1588162229](https://user-images.githubusercontent.com/34129384/80594513-6c149c80-8a23-11ea-943b-9abd99815090.png)

**Comment by jkrod** [comment]
Didnt close automatically, The linked pull request is merged. So I am closing manually

**Comment by T-Hauge** [comment]
This issue have been fixed, but was accidently overwritten by PR #484.
