### ISSUE TITLE
As a guardian removing a timer deletes the activity

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/weekplanner-OLDUI#461]
**Describe the bug**
When a guardian removes a timer, the whole activity is deleted.

**To Reproduce**
1. Create an activity
2. Add a timer to the activity
3. Remove the timer
4. Press the back button
5. The activity is now deleted

**Expected behavior**
For the activity to still be there.

**Actual behavior**
The activity is deleted. Also exceptions are thrown because the activity is no longer there.

**Video**
https://streamable.com/txjwa7

**Environment (please complete the following information):**
- OS: Android
- Emulator? Yes

**Additional context**
It might be related to #444, but I'm not sure.

**Comment by Rsvend17** [comment]
Step 3 should be, that you remove the timer and not the activity

**Comment by giano574** [comment]
Moved to https://github.com/aau-giraf/web-api/issues/140
