### ISSUE TITLE
Missing error message when marking an invalid number of week plans

### ISSUE THREAD

**Issue by MrPekar98** [aau-giraf/weekplanner-OLDUI#464]
**Describe the bug**
When marking either non or too many week plans and pressing "Rediger", nothing tells the user what is missing.

**To Reproduce**
1. Go to week plans of a citizen.
2. Press the edit button and select multiple or no activities.
3. Press the "Rediger" button.
4. No dialog pops up telling the user what is wrong.

**Expected behavior**
A dialog tells the user either too many or no activities have been selected.

**Actual behavior**
Nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/32843490/80597531-463dc680-8a28-11ea-9fb9-f2ebb582fe0d.png)

**Comment by joandrsn** [comment]
Question:
Currently there is actually a change in color.
This is the `enabled` parameter on the "Redigér"-button.
https://github.com/aau-giraf/weekplanner/blob/a8ef6f165e50ccfd06a1bde124f679045dcc895a/lib/screens/weekplan_selector_screen.dart#L248-L249

It simply changes based on if there is 1 week selected or not.

So with this change, the button should always be enabled, and display a message if you make an error, is this correctly understood?

Disabled:
![image](https://user-images.githubusercontent.com/5766695/80687280-5ad29b00-8aca-11ea-813f-406282935016.png)

Enabled:
![image](https://user-images.githubusercontent.com/5766695/80687263-527a6000-8aca-11ea-9f5c-bab326d4e39d.png)

**Comment by MrPekar98** [comment]
Exactly!

**Comment by elaurs** [comment]
Another alternative could be to remove the edit button, when marking more than one week plan or not having marked any. There just needs to be a better indication of when it is possible to edit and when it is not. So there just isn't a button that does nothing.

**Comment by Lortemanden** [comment]
joandrsn yes it is correctly understood. 

elaurs the button should not be removed since it would make it harder for the guardians to figur out where the edit function is.

**Comment by MrPekar98** [comment]
A simple dialog pop-up would do.
