### ISSUE TITLE
As a guardian, I would like to see the setting "Tegn for udførsel"

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/weekplanner-OLDUI#465]
**Describe the bug**
As an extension to #376 the setting "Tegn for udførsel" has not received the same treatment as the other settings.

**To Reproduce**
1. Go to settings on a user

**Expected behavior**
I would expect it to say "Fjern", "Flueben" or "Grå ud"

**Actual behavior**
It is blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/5766695/80598780-23acad00-8a2a-11ea-8553-fb5892de8ef4.png)

**Environment (please complete the following information):**
- Emulator? Yes

**Additional context**
Might be dependent on #460

**Comment by elaurs** [comment]
Det er meningen, at det ikke skal vises for guardian. Det kommer af issue #65 😄
