### ISSUE TITLE
Not all Danish letters are supported for username when creating a citizen

### ISSUE THREAD

**Issue by elaurs** [aau-giraf/weekplanner-OLDUI#467]
**Describe the bug**
When trying to create a new citizen with an 'æ', 'ø' or 'å' in the username, it is not possible to save it and no error message is displayed.

**To Reproduce**
1. Go to create a new citizen
2. Write 'mø' in all the fields
3. Press 'Gem borger'
4. Nothing happens

**Expected behavior**
The user with 'æ', 'ø' or 'å' in their username in should be created or maybe som kind of error message should be display.

**Actual behavior**
Nothing happens when pressing the button.

**Comment by jbjarn17** [comment]
Might be related to issue #431
