### ISSUE TITLE
Activity timer completion sound is still emitted when you are logged out

### ISSUE THREAD

**Issue by Rsvend17** [aau-giraf/weekplanner-OLDUI#468]
**Describe the bug**
Activity timer completion sound is still emitted when you are logged out and when in the login screen if an activity timer is running and completes, when logged out. 

**To Reproduce**
See video in the link below.

**Expected behavior**
Timer should not emit a sound when you are not logged in

**Actual behavior**
Timer emits a sound when running, even if logged out of the app. 

**Video**
https://streamable.com/27e9d1

**Comment by Rsvend17** [comment]
OBS. video needs to be watched with sound on.

**Comment by Kaliahh** [comment]
This is intentional, not bug
