### ISSUE TITLE
When displaying a single day on a weekplan activities are very big

### ISSUE THREAD

**Issue by Simon97** [aau-giraf/weekplanner-OLDUI#469]
**Describe the bug**

**To Reproduce**
1. Go to settings and select and select the option to only show one day
2. Show a weekplan and the activities should now be as wide as the screen. Especially in landscape mode this is a problem.

**Expected behavior**
I expected to be able to see more than a half activity on screen

**Actual behavior**
Just a half activity is visible at a time

![78117304-cb23c900-7405-11ea-903e-65f948a4b792](https://user-images.githubusercontent.com/13853315/80601994-d979fa80-8a2e-11ea-8e75-94c9d4c426b8.png)

**Environment (please complete the following information):**
- OS: Android
- Phone: Sony tablet?

**Comment by mathiasandresen** [comment]
@aau-giraf/sw613f20 
We have 2 proposed solutions:
![billede](https://user-images.githubusercontent.com/5781825/80687922-5195fe00-8acb-11ea-8d81-4a00472ed391.png)
or
![billede](https://user-images.githubusercontent.com/5781825/80687964-607cb080-8acb-11ea-86a3-a2dfd6beb29d.png)
Is any of them preferred, or do you have another proposition

**Comment by Lortemanden** [comment]
I think the first one would be the best.
