### ISSUE TITLE
Missing error message when trying to create a citizen with a username already in use

### ISSUE THREAD

**Issue by melanieselman** [aau-giraf/weekplanner-OLDUI#471]
**Describe the bug**
When creating a new citizen with a username that is already used in another citizen, no error message is shown indicating the reason why the citizen can not be saved. 

**To Reproduce**
1. Go to screen where you can choose between citizens and add a new citizen.
2. Click on create a citizen.
3. Create a citizen with a specific username and save it.
4. Create a new citizen with the same username.
5. See how no error message is shown indicating that you are trying to create a citizen with an already existing username.

**Expected behavior**
An error message should show telling the user that they are trying to create a new citizen with an already existing username, and they should therefore choose a different username.

**Actual behavior**
It is not possible to save the citizen, but there is no error message telling you why.

**Comment by jbjarn17** [comment]
I think this is related to issue #431
