### ISSUE TITLE
Guardians and citizens are able to run multiple simultaneous timers.

### ISSUE THREAD

**Issue by DumbLol** [aau-giraf/weekplanner-OLDUI#472]
**Describe the bug**
Citizens and guardians able to run multiple timers at once.

**To Reproduce**
1. Create activities with timers.
2. Start individual timers.
3. wait for completion noise.

**Expected behavior**
Once a timer is running, expected behavior would be the inability to start another activity's timer.
A citizen could start an entire weeks timers at the same time.

**Actual behavior**
Timers started without issue.

**Environment (please complete the following information):**
- OS: android
- Emulator? yes.

**Comment by Lortemanden** [comment]
Not necessarily a bug. So we will ask the customers to the next meeting.

**Comment by T-Dawq** [comment]
Closed after speaking with customers and they did not see this as an issue.
