### ISSUE TITLE
The color saturation for a weekplanner in citizen mode is different from the guardians

### ISSUE THREAD

**Issue by tuanvu29** [aau-giraf/weekplanner-OLDUI#473]
**Describe the bug**
For a newly created citizen the the color saturation for its weekplanner in citizen mode is different from when your in guardian mode.

**To Reproduce**
1. Create new citizen
2. Add a new weekplan
3. Open that weekplan and change to citizen mode

**Expected behavior**
Same color as in guardian mode
![image](https://user-images.githubusercontent.com/54982115/80603960-632ac780-8a31-11ea-8632-255643bc0ec0.png)

**Actual behavior**
Different color saturation in citizen mode
![image](https://user-images.githubusercontent.com/54982115/80603998-6f168980-8a31-11ea-81af-dec3c16d44e0.png)

**Screenshots**

**Environment (please complete the following information):**
- Emulator?
- Phone [e.g. Iphone X, Pixel 2]
- APK Version [e.g. 22]

**Additional context**

**Comment by MrPekar98** [comment]
Fixed in web-api.
