### ISSUE TITLE
With a lot of activities on a single weekplan, the activities sometimes jump to the bottom of the day when moved

### ISSUE THREAD

**Issue by Simon97** [aau-giraf/weekplanner-OLDUI#474]
**Describe the bug**
With a lot of activities on a single weekplan, a activity sometime jump back to the bottom when moved (please watch the videos) 

**To Reproduce**
1. Add a lot of activities to a weekplan
2. Try to move an activity to a new spot on the same day
3. See error

**Expected behavior**
The activity should stay where I place it

**Actual behavior**
The activity jumps to the bottom of the day

**Environment (please complete the following information):**
- OS: [Android]
- Emulator
- Phone [Sony tablet]
[bug.zip](https://github.com/aau-giraf/weekplanner/files/4552150/bug.zip)

**Comment by Kaliahh** [comment]
Can only be reproduced on emulator, doesn't happen on an actual phone/tablet

**Comment by MichelleTerpling** [comment]
Possibly related to #588
