### ISSUE TITLE
As a guardian I would like to be able to log into the system using a username and password, so that I can see my associated citizens

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#48]
- [x] Ensure that login works correctly (cannot login with incorrect information)
- [x] Ensure that login matches prototype and design guide
- [x] A loading spinner is shown while contacting API, so the user does not think the app is frozen

**Comment by sipman** [comment]
This feature is implemented somewhat, there is a need to make improvements on the Screen and to test that the implementation is correct, if not, correct it to specs.

**Comment by Tricky12321** [comment]
There is still a need for loading spinner and information about the user entered wrong username and/or password. There is also no way to test if the API is working
