### ISSUE TITLE
When uploading a large image to a new weekplan, the image is not uploaded properly

### ISSUE THREAD

**Issue by mads-bo** [aau-giraf/weekplanner-OLDUI#482]
**Describe the bug**
When I upload an image taken with my phones camera, the image shows as a loading icon, instead of the actual image. When creating a new activity and searching for the image, the image still shows as a loading icon.

**To Reproduce**
1. Create a new activity
2. Choose an image from the phones internal storage
3. Save and see the error

Try also creating a new activity again and searching for the image, to see the error again

**Expected behavior**
The image to show up as itself

**Actual behavior**
Image shows as a loading icon

**Screenshots**

**Environment (please complete the following information):**
- Galaxy S9 running Android 10

**Additional context**

**Comment by T-Dawq** [comment]
**Alternative solution 1**
Define a reasonable size limit (e.g. the app should at the very least be able to support photos taken with the device's camera) and make sure the application supports this.
A popup should tell the user what is wrong if the photo exceeds the limit.

**Alternative solution 2**
Figure out the current size limit and resize the image.

**Comment by MichelleTerpling** [comment]
Can not be replicated
