### ISSUE TITLE
As a guardian I would like to be able to log out so that the system is not left logged in after I’m done using it.

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#49]
Tasks:

- [ ] Put a log out icon in the GirafAppBar
- [x] Create BLoC that sends request to API and removes auth token
- [x] Redirect to login screen after successfully logging out

**Comment by sipman** [comment]
This feature is to place an logout-icon in the GirafAppBar and create a BLoC that can send the request to the web-api and remove the auth token from the app. The functionality of redirecting to the login screen and remove all access to the other screens are already implemented.

**Comment by Tekrus** [comment]
Currently blocked @aau-giraf/sw611f19 working on fixing login core.
Please ping us when this is no longer blocking. 😸
