### ISSUE TITLE
As a developer I want the amount of citizens to be reduced for the next semester

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#491]
**Is your feature request related to a problem? Please describe.**
At the moment, the application is cluttered with citizens. This should be cleaned up for the next semester of students.

**Describe the solution you'd like**
The list of citizens should contain BirkenBorger1, BirkenBorger2, BirkenBorger3, BirkenBorger4 and BirkenBorger5. 

--------------------------------------------------------
**This should be done at the end of the sprint**

**Comment by frederikspang** [comment]
Migration has been run, and deleted a ton of citizens, in all Environments.
