### ISSUE TITLE
Refactor the code so we don't use the Observable class

### ISSUE THREAD

**Issue by Simon97** [aau-giraf/weekplanner-OLDUI#499]
**Is your feature request related to a problem? Please describe.**

In the Weekplanner application, we are using the Observable class from the rxdart library but it is not a part of the newest version.
The task is to refractor the code and upgrade the dependencies in order to block further use of deprecated classes.

**Describe the solution you'd like**
A solution is described at the following link:
https://pub.dev/packages/rxdart#-changelog-tab-

**Describe alternatives you've considered**
Change the code manually?

**Additional context**
<img width="553" alt="Skærmbillede 2020-05-06 kl  08 42 43" src="https://user-images.githubusercontent.com/13853315/81144981-927f8e00-8f75-11ea-898f-1d65c82c9874.png">

The same problem happens in web api:  https://github.com/aau-giraf/api_client/issues/56

**Comment by jkrod** [comment]
**Info:**

Synes ikke jeg kunne se andet end en changelog for RX Dart librariet i det link. Men har fundet et script der vidst kan køres via en flutter command for at opdatere koden. Check evt. lige selv, hvis man arbejder på dette issue.

![image](https://user-images.githubusercontent.com/34282060/81152022-d7a9bd00-8f81-11ea-8303-60612f546e92.png)
**FRA:**
https://stackoverflow.com/questions/59336428/observable-is-deprecated-in-rxdart-0-23-1
