### ISSUE TITLE
As a citizen I would like different ways to mark an activity as done so that it fits my personal preference

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#5]
The following is different ways citizens would like to mark an activity as done:

By adding a checkmark (√). ( This will most likely be implemented in #75 )
Removing the activity entirely
Greying the activity

**Comment by Eduardsen** [comment]
![greyout](https://user-images.githubusercontent.com/22811794/53288427-0f1ab800-3788-11e9-98b5-72445c813235.PNG)
![removecompleted](https://user-images.githubusercontent.com/22811794/53288428-0f1ab800-3788-11e9-8db3-26e5d9fd11b7.PNG)
![checkmark](https://user-images.githubusercontent.com/22811794/53288429-104be500-3788-11e9-96ee-f40725c9d59d.PNG)

**Comment by Tekrus** [comment]
Duplicate of #65
