### ISSUE TITLE
As a guardian I would like to be able to choose which week plan to show the citizen so that I can have multiple plans available to each citizen

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#50]
Tasks: 
- [x] Create a screen for the "choose week" screen, refer to prototypes
- [x] Make a BLoC to pass on information

This story blocks #51

**Comment by sipman** [comment]
This feature is to create a screen to show a list of all existing weekplans.

The main tasks are:
- Make a screen for the "choose week" screen.
- Make a BLoC to delegate the information.

**Comment by sipman** [comment]
This task should be done before #51

**Comment by LukasRH** [comment]
This is closed with #96
