### ISSUE TITLE
Update buttons to follow the design guide

### ISSUE THREAD

**Issue by Nannanas** [aau-giraf/weekplanner-OLDUI#502]
**Is your feature request related to a problem? Please describe.**
The design guide for the disabled buttons has been updated. 

**Describe the solution you'd like**
The disabled buttons in the application should follow the design guide.

**Additional context**
link to the design guide: https://aau-giraf.github.io/wiki/development/design_guide/

**Comment by Kaliahh** [comment]
Solved by #527 (#556)
