### ISSUE TITLE
Re-navigating to activity where cancelling the activity was undone only show the 'Fortryd' button screen

### ISSUE THREAD

**Issue by MrPekar98** [aau-giraf/weekplanner-OLDUI#503]
**Describe the bug**
When entering an activity where cancelling of the activity was undone previously, the screen only show the 'Fortryd' screen. Furthermore, pressing the 'Fotryd' button does not do anything.

**To Reproduce**
1. Go to an activity.
2. Cancel the activity and press 'Fortryd' immediately after.
3. Go back to the week plan screen.
4. Enter the same activity.
5. See that only the 'Fotryd' screen appear and the button does not do anything.

**Expected behavior**
The screen that shows the pictogram of the activity and the associated timer appears.

**Actual behavior**
Only the 'Fotryd' screen appear when entering an activity where the user previously cancelled the activity and then immediately undid it.

**Screenshots**
Below is the screen when re-entering an activity with the above mentioned conditions:

![image](https://user-images.githubusercontent.com/32843490/81227513-d95c9a80-8fec-11ea-9545-a8f48ebdf37d.png)

**Environment (please complete the following information):**
- OS: Android
- Emulator? Yes
- Phone: 7.3 Foldable

**Comment by soenderby** [comment]
Unable to reproduce the bug
