### ISSUE TITLE
As a guardian I would like to be able to create a new week plan so that it is suited to the given citizens week

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#51]
- [ ] Screen for adding new week plan that contains the following information:
-     Name of weekplan
-     Year of the weekplan
-     Week number (of the year)
-     Pictogram selector (This should use the same pictogram searcher as new activity see #46)
-     A button to select a week template (the feature do not require implementation of the week template feature, only the button)
-     A button to save

- [ ] A BLoC to archieve the functionality, or implementation of existing BLoCs
- [ ] Redirect to show weeks after adding a new week plan

**Comment by sipman** [comment]
This feature surrounds the ability to click the "+"-button on the "Choose week"-screen and then see a screen from where I can construct a new week. In forming a new week, I should be able to base it of a week template. This feature does NOT include creating the week template part, only creation of a new week, but please ensure that there is a button for this functionality in the feature — referer to the PO-groups prototypes for any UI questions.

Main activities within this feature:
- Make a screen for constructing a new weekplan, the necessary field are:
  - Name of weekplan
  - Year of the weekplan
  - Week number (of the year) 
  - Pictogram selector (This should use the same pictogram searcher as new activity see #46)
  - A button to select a week template (the feature do not require implementation of the week template feature, only the button)
  - A button to save
- Make BLoC's to achieve the functionalities, and there might be needed many new BLoC's and use of possible existing ones.
- Make the "Choose week"-screen show the newly created screen.

**Comment by sipman** [comment]
This feature could possible "conflict" with #52 and #50
