### ISSUE TITLE
Adding activities to a weekplan and then editing the weekplan, removes the added activities

### ISSUE THREAD

**Issue by Markusjeppesen** [aau-giraf/weekplanner-OLDUI#511]
**Describe the bug**
When you add activities to a weekplan, and then edit the week plan by changing its pictogram, the activities get removed from the weekplan.

**To Reproduce**
1. Choose a weekplan for citizen
2. Add a number of activities to a day in the week
3. Navigate back to the weekplan selector screen and edit the same weekplan
4. When editing the weekplan, change the pictogram, and click save.
5. Click on the edited weekplan, and the activities you added before are no longer there.

**Additional context**
Here is a video visualizing the bug:
[editBug.zip](https://github.com/aau-giraf/weekplanner/files/4597685/editBug.zip)

**Comment by Kaliahh** [comment]
Cannot be reproduced, closing issue
