### ISSUE TITLE
Week models in WeekplansBloc are not updated when activities are updated

### ISSUE THREAD

**Issue by MrPekar98** [aau-giraf/weekplanner-OLDUI#516]
**Describe the bug**
When updating an activity, such as its timer, the week models are not updated. When updating a week model and navigating to the _WeekplanSelectorScreen_, the old week models are reloaded from the _weekModels_ stream in _WeekplansBloc_. Therefore, changes to activities are not applied.

**To Reproduce**
This is just one example, where the old week models are reloaded into a week plan.
1. Go to week plan and add a new activity.
2. Enter the activity, create a timer, and then delete the timer again immediately.
3. Go back twice to the week plan selector.
4. Navigate to the same week plan again.
5. See that the timer is still assigned to the newly added activity even though we deleted it.

**Expected behavior**
The _weekModels_ stream in _WeekplansBloc_ contains the newest week models.

**Actual behavior**
 Old week models are not reloaded into week plans every time the user navigates to the week plan selector.

**Environment (please complete the following information):**
- OS: Android

**Comment by giano574** [comment]
Will be fixed when `fixes_webapi98` is merged
