### ISSUE TITLE
Random days are shown in mon-fri view for citizen

### ISSUE THREAD

**Issue by Simon97** [aau-giraf/weekplanner-OLDUI#517]
**Describe the bug**
If the option monday to friday are chosen in settings, random days are shown for the citizen.

**To Reproduce**
1. Set the Antal dage setting to Vis mandag til fredag.
2. Go back and switch to citizen mode
3. Try to change orientation.

**Expected behavior**
I expected that the days monday to friday are shown like before I change the orientation

**Actual behavior**
A clear and concise description of what actually happened.
Random days are shown.

**Screenshots**
Before change of orientation:
![Screenshot_1589113977](https://user-images.githubusercontent.com/13853315/81499339-34331200-92cb-11ea-80a2-f154e4f271ad.png)

After change of orientation:
![Screenshot_1589114026](https://user-images.githubusercontent.com/13853315/81499349-43b25b00-92cb-11ea-9ddf-4ab4d98ea4dc.png)

**Environment (please complete the following information):**
- OS: Android
- Emulator: Yes :D

**Comment by giano574** [comment]
Is it not correct behaviour to show the next five days?
