### ISSUE TITLE
Completed activites leave empty space in citizen mode

### ISSUE THREAD

**Issue by ssrika17** [aau-giraf/weekplanner-OLDUI#525]
**Describe the bug**
When the option "Fjern aktivitet fra borgeren" has been selected, completed activities leave empty space on the weekplan.

**To Reproduce**
1. Go to user settings.
2. Choose "Fjern aktivitet fra borgeren" in the "Tegn for udførelse" section.
3. Go to a week plan that has completed activities and enter citizen mode.
4. See that there are empty space between the completed activities.

**Expected behavior**
The activity should be removed completely without leaving empty space

**Screenshots**
![image](https://user-images.githubusercontent.com/37399231/81803099-7a7cb100-9517-11ea-961f-251a866f3cdd.png)

**Comment by Lortemanden** [comment]
This is not a bug, but something the customer asked for.
