### ISSUE TITLE
As a citizen I want to be able to log in so that I can access my current week plan without the help of a guardian

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#528]
**Is your feature request related to a problem? Please describe.**
Currently, only guardians can log in to the application which means that a guardian will have to log in on a citizen's personal device in order to make a week plan available to the citizen. This is suboptimal for more independent citizens who are able log in themselves.

This issue is related to #530 

**Describe the solution you'd like**
The first login on the device should be text-based (username and password is created when the citizen is registered).
![2020f_27_CIT_WP528 Citizen login](https://user-images.githubusercontent.com/55434874/82754108-1ab1c000-9dcb-11ea-823e-2abc62ec5e30.png)
After the first login, a pictogram password is used (this password is registered in [weekplanner#530](https://github.com/aau-giraf/weekplanner/issues/530)). The ten pictogram options should be determined by a setting for the citizen.
![2020f_27_B_CIT_1_WP528 Citizen login](https://user-images.githubusercontent.com/55434874/82754148-5482c680-9dcb-11ea-9cb2-c269c46177b8.png)
When a pictogram is dragged to the bar at the bottom it should be duplicated so that pictograms can be used multiple times in the same password without having duplicates among the ten options.
![2020f_27_B_CIT_2_WP528 Citizen login](https://user-images.githubusercontent.com/55434874/82754235-e094ee00-9dcb-11ea-9b3b-3cf6e89f4537.png)
If one of the buttons are pressed and a different citizen or a guardian logs in on the device, the original citizen will have to start over from the text-based login screen.
![Login (1)](https://user-images.githubusercontent.com/55434874/82754365-be4fa000-9dcc-11ea-894e-db118346ab37.png)

**Additional context**
Depends on [weekplanner#530](https://github.com/aau-giraf/weekplanner/issues/530).

**Comment by dkalaxdk** [comment]
Can be implemented using: aau-giraf/web-api#159
As the image has can be used to determine whether the password is correct.
By comparing the selected images with the hash of the images stored in the database.
