### ISSUE TITLE
As a guardian I would like to be able to mark activities as completed

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/weekplanner-OLDUI#529]
**Is your feature request related to a problem? Please describe.**
Guardians should be able to mark activities as complete like the citizens can.

**Describe the solution you'd like**
To be added.

**Comment by T-Dawq** [comment]
Ignore mention. Was a mistake.

**Comment by dkalaxdk** [comment]
Prototype:
![2020f_26_GUA_WP529](https://user-images.githubusercontent.com/13720707/94793202-64925e80-03da-11eb-9038-c08a041e78a8.png)
