### ISSUE TITLE
'Overståede Uger' does not update correctly

### ISSUE THREAD

**Issue by pegede17** [aau-giraf/weekplanner-OLDUI#538]
**Describe the bug**
After editing the last weekplan from the 'Overståede Uger' section to become a future week instead and the 'Overståede Uger' section becomes empty, a spinning circle is displayed as if it is trying to load a weekplan.

**To Reproduce**
1. Create a weekplan with a year less than the current year
2. Make sure this is the only weekplan in 'Overståede Uger'
3. Edit the weekplan with a year greater than the current year

**Expected behavior**
No spinning circle

**Actual behavior**
A grey box with a spinning circle.

**Screenshots**
![image](https://user-images.githubusercontent.com/54982103/82192993-0a927000-98f5-11ea-853a-5aabdac9b893.png)

**Environment (please complete the following information):**
- OS: [Android]
- Emulator - Yes
- Nexus 9
- APK Version - 29

**Additional context**

**Comment by AAU-Phil** [comment]
The root of this issue is that "overståede uger" cant go from containing weekplans to containing no weekplans when editing. 
It is however possible to delete the last weekplan in "overståede uger" without problems.

**Comment by Markusjeppesen** [comment]
The error happens in the "reformatWeekDetailsToObservableList" method in the weekplan_selector_bloc.dart file. 

This method is called multiple times in the getAllWeekInfo method, after a week plan is edited. First, the method returns "details[0].map((WeekModel plan) => <WeekModel>[plan])" (causes the error), and then next time it is called it returns "Observable.empty()".

**Comment by ProgDaniel** [comment]
In the **weekplan_selector_bloc.dart**, the stream that tranfers the weekplans, _weekNameModelsList\__, does not get the new weekplans / update itself after performing an edit, thus it maps the old list of weekplans. If one of the lists ("overstående/kommende ugeplan") is empty, then it will map an empty item in the _reformatWeekDetailsToObservableList_ method, which causes the error.
