### ISSUE TITLE
As a guardian I would like to be able to switch to citizen mode so that I can give the tablet to the citizen for use.

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#54]
Tasks:
- [x] There should be an icon in the GirafAppBar that changes to citizen mode

**Comment by Tekrus** [comment]
Is this fixed in #23 ?

**Comment by User12837985123** [comment]
We are working on it in #23, and we are now working on this user story aswell.

**Comment by Bjerkk** [comment]
Citizen mode being the display of only a single weekday.

**Comment by KVISDAOWNER** [comment]
Part of a now bigger user story, namely #132

**Comment by KVISDAOWNER** [comment]
Part of a now bigger user story, namely #132
