### ISSUE TITLE
As a guardian i would like to be able to hide or collapse "Overståede uger" 

### ISSUE THREAD

**Issue by AAU-Phil** [aau-giraf/weekplanner-OLDUI#540]
**Is your feature request related to a problem? Please describe.**
The "Overståede uger" takes up a lot of room on the weekplan selection screen, especially on landscape mode, so having the option to hide it would make the upcoming weekplans easier to navigate and select from.

**Describe the solution you'd like**
An ability to hide the "overståede uger" either with a button or a collapsible

**Comment by soenderby** [comment]
When the "Overståede uger" bar is pressed, the weekplans contained within should be hidden and bar should then be placed at the bottom of the screen.
![2020e_1_1_GUA_WP540](https://user-images.githubusercontent.com/33911621/94660382-e06ea700-0305-11eb-9524-3e972243a19e.PNG)
When the "Overståede uger" bar at the bottom of the screen is pressed, the bar should return to its previous location, and the weekplans should be visible once again.
![2020e_1_2_GUA_WP540](https://user-images.githubusercontent.com/33911621/94660387-e2386a80-0305-11eb-8b35-fc473c29134d.PNG)
