### ISSUE TITLE
As a guardian I would like to have an indication that informs me that a "Brugernavn" is used when adding new user

### ISSUE THREAD

**Issue by tuanvu29** [aau-giraf/weekplanner-OLDUI#542]
**Is your feature request related to a problem? Please describe.**
When creating a new user with the required information, if I use an existing "Brugernavn", the screen does not tell me what is required and "gem borger" button is clickable but do nothing. 

**Describe the solution you'd like**
An indication that shows me if I already have used the "Brugernavn"

**Comment by dkalaxdk** [comment]
Closed, as fixed by #471
