### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by Mustafa-ALD** [aau-giraf/weekplanner-OLDUI#568]
**Describe the bug**
Den burde ikke give beskeden "something went wrong". Det er taget fra api error. Error skal bare være på dansk og forståeligt for brugeren.

**To Reproduce**
1. Go to 'Create user'
2. Make new user
3. Use same username as another user

**Expected behavior**
Dansk error message "Brugernavn er allerede brugt"

**Actual behavior**
"Something went wrong..."

**Screenshots**
yes
![Untitled](https://user-images.githubusercontent.com/43955099/94657021-27a66900-0301-11eb-8ab4-a9d0856ed9ce.png)

**Environment (please complete the following information):**
- OS: Android 
- Emulator? yes
- Phone Pixel 2
- APK Version: 28

**Comment by smh87** [comment]
Hvordan får i fejlen? Sker det når i har tabs i brugernavn?

**Comment by ProgDaniel** [comment]
Fejlen sker fordi der er en samling af special tegn som ikke kan komme ind i username string, hvor tab (\t) er en af dem. Derfor skal issuet udvides til username validation method
