### ISSUE TITLE
As a citizen I would like for the number of days shown in the week plan to change when the orientation of the device changes

### ISSUE THREAD

**Issue by MichelleTerpling** [aau-giraf/weekplanner-OLDUI#569]
**Describe the solution you'd like**
When changing the orientation of the device the week plan should show a different number of days. For example when the device is in landscape mode the week plan should show the entire week, and when the device is in portrait mode the week plan should only show one day. 
The number of days shown in either mode should be customizable: see issue #571 
Until this issue is implemented, the standard setting should be the number of days selected in the settings menu when in landscape mode, and one day when in portrait mode.

**Additional context**

**Comment by dkalaxdk** [comment]
When showing one day:
![2020e_9_CIT_2_WP569 Orientation, days change](https://user-images.githubusercontent.com/13720707/97304191-ae485a80-185b-11eb-9a56-3287b231775a.png)

When showing two days:
![2020e_9_CIT_3_WP569 Orientation, days change](https://user-images.githubusercontent.com/13720707/97304330-dd5ecc00-185b-11eb-991a-d879d6db6cfb.png)

**Comment by Lildhansen** [comment]
Like issue #571 , this issue is also closed with [this](https://github.com/aau-giraf/weekplanner/pull/890) pull request
