### ISSUE TITLE
As a guardian I would like to be able to change how many days are shown in the week plan depending on the orientation of the device

### ISSUE THREAD

**Issue by MichelleTerpling** [aau-giraf/weekplanner-OLDUI#571]
**Describe the solution you'd like**
In the settings menu it should be possible to select a different number of days to be visible in the week plan for a citizen depending on whether the device is in landscape or portrait mode.

Default should be 1 for portrait mode.

Related issue: #569 

**Additional context**

**Comment by Kaliahh** [comment]
![2020e_8_A_GUA_2_WP471Orientation change settings](https://user-images.githubusercontent.com/13720707/97304184-ac7e9700-185b-11eb-9c6b-60372af376ef.png)
In the settings menu, there should be an option for changing the amount of days shown in the week plan, when changing the orientation of the app.
