### ISSUE TITLE
As a user i would like to sort my pictograms by categories when searching.

### ISSUE THREAD

**Issue by dkalaxdk** [aau-giraf/weekplanner-OLDUI#572]
**Describe the solution you'd like**
When searching the pictograms, i would like to be able to sort my search into; "Alle pictogrammer", "Standard piktogrammer", "Dine pictogrammer".

**Additional context**
Prototype for the layout when searching, ignore the trashcan on the photos, as this is not related to this issue.
![2020f_12_GUA_3_WP273 Delete personal pictogram](https://user-images.githubusercontent.com/13720707/94663971-9805b800-030a-11eb-8424-7e8cf0eae0cd.png)

![2020f_12_GUA_3_WP273 Delete personal pictogram](https://user-images.githubusercontent.com/13720707/94663925-89b79c00-030a-11eb-932b-b5d3fc6b9ea7.png)

![2020f_12_GUA_1-1_WP273 Delete personal pictogram](https://user-images.githubusercontent.com/13720707/94663823-6b51a080-030a-11eb-931a-96eab89850ae.png)

**Comment by Kaliahh** [comment]
Possibly replaced by #639 and #640

**Comment by Kaliahh** [comment]
Replaced by #639 and #640
