### ISSUE TITLE
As a Guardian i would like to be able to rename choiceboards.

### ISSUE THREAD

**Issue by dkalaxdk** [aau-giraf/weekplanner-OLDUI#576]
**Describe the solution you'd like**
Guardians should be able to rename specific choiceboards of citizens.

**Comment by Kaliahh** [comment]
### First the choiceboard is clicked on
![2020e_4_GUA_1_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089040-f7f1c980-0723-11eb-9387-eced4f8bdebf.png)

### Then the guardian can click on the text field
![2020e_4_GUA_2_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089042-f88a6000-0723-11eb-863d-2bfd7790dbc6.png)

### The guardian can then change the name
![2020e_4_GUA_3_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089043-f88a6000-0723-11eb-89e8-02665b9ffdea.png)
![2020e_4_GUA_4_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089044-f922f680-0723-11eb-9b95-4c967a7d8b9a.png)

### The guardian can then save the new name
![2020e_4_GUA_5_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089045-f922f680-0723-11eb-8290-f06458915d3f.png)
![2020e_4_GUA_6_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089047-f9bb8d00-0723-11eb-99f9-88a6d6e355a9.png)

### The guardian can also choose to restore the standard name
![2020e_4_GUA_7_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089048-f9bb8d00-0723-11eb-9678-4bb6a8a1f8cf.png)

### By clicking on "Hent standard" the standard name is restored
![2020e_4_GUA_8_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089049-fa542380-0723-11eb-85dc-0caa4671b2a7.png)

### The restored name can then be saved
![2020e_4_GUA_9_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089051-fa542380-0723-11eb-8984-64b1bcf046f5.png)
![2020e_4_GUA_10_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089052-faecba00-0723-11eb-9c2f-917cff6dfd0a.png)
![2020e_4_GUA_1_WP576  Choice board renaming](https://user-images.githubusercontent.com/42242841/95089040-f7f1c980-0723-11eb-9387-eced4f8bdebf.png)

**Comment by Mustafa-ALD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 576](https://trello.com/c/kO11UrAO/26-issue-576)
