### ISSUE TITLE
As a guardian I would like to be able to mark an activity as cancelled so that I can let the citizen know that an activity has been cancelled

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#58]
Can conflict with #59 which implements cancelling multiple activities

**Comment by andpaacoke** [comment]
On the detail page of an activity the guardian can press the cancel button to cancel an activity which is indicated by the red cross.
![Aktivitet - 6](https://user-images.githubusercontent.com/22811754/55875316-1dd0f900-5b95-11e9-8da8-4ece0d011dcd.png)

**Comment by Tekrus** [comment]
@aau-giraf/sw608f19 you have been assigned to this! ⚒
