### ISSUE TITLE
Upgrade Flutter

### ISSUE THREAD

**Issue by ggAlexS** [aau-giraf/weekplanner-OLDUI#584]
**Is your feature request related to a problem? Please describe.**
There are deprecated functions being used in the application. This prevents upgrading to the new flutter version. 

**Describe the solution you'd like**
Fix the application so the flutter version can be upgraded

**Comment by Kaliahh** [comment]
Please include which functions are deprecated.

**Comment by JeppeKLau** [comment]
The deprecated functions we have noticed are from the injector package. If you try running `flutter upgrade` and `flutter pub get` and then attempt to build the project, you will get [this](https://pastebin.com/kr7RdnEr) output.
Furthermore, we should look into the option of updating the SDK to a newer version. The same should go for the supported versions of Android and iOS. iOS in particular is very much needed, as the `IPHONEOS_DEPLOYMENT_TARGET` is set to 8.0; Xcode says the range of supported deployment target versions is between 9.0 and 14.0.99. And for Android, do we really want to support systems all the way back to 4.1 lollipop?

**Comment by Jaffenheimer** [comment]
Potentielt er denne issue meget stor alt efter hvor nemt det er at fjerne issuesne igen. se issue 110 i api_client

**Comment by danielalexlarsen** [comment]
og HUSK at tilpas Github Actions (tests) til at target den nye version af frameworket

**Comment by JakobTopholt** [comment]
"Deleted"

**Comment by JakobTopholt** [comment]
We'd like version 3.3.6 as it is the newest version from the stable channel as of now, if this causes issues (as it is 1 day old as of now)

https://docs.flutter.dev/development/tools/sdk/releases

![Image](https://user-images.githubusercontent.com/74545500/199243910-08d8835a-76db-414b-ad68-fa63cbcf38ec.png)

Here is a list of conflicts currently (01/11/2022) preventing an upgrade of flutter to from 2.0.5 to 3.3.6

https://stackoverflow.com/questions/65277843/flutter-list-is-deprecated This should help with the first conflict.

**Comment by JakobTopholt** [comment]
Dart skal også opdateres Dart.
