### ISSUE TITLE
Moving activities in a weekplan should not cause the whole weekplan to reload

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#587]
**Is your feature request related to a problem? Please describe.**
When moving activities, the whole weekplan reloads. All cancelations and completions are removed and added again. It is especially bad if pictogram text is visible, as it causes the whole plan to jump around (See video).

**Describe the solution you'd like**
The weekplan should not visibly go through a reload as seen in the video and described above. It should just move the activity.

**Describe alternatives you've considered**
Hide the whole weekplan until the reload is finished.

**Additional context**

Related to aau-giraf/web-api#19

![ezgif-6-e9f84d0100ae](https://user-images.githubusercontent.com/42242841/95453485-3dec9e80-096b-11eb-9694-c5d5ff65270a.gif)

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 587](https://trello.com/c/l1LYH6PV/55-issue-587)
