### ISSUE TITLE
As a guardian I would like to be able to cancel and copy multiple activities at once by marking them so that I don't have to manually do it for each activity I want to change

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#59]
Mark mode was done in #57 by @aau-giraf/sw613f19 but needs the functionality to cancel or copy activities. 

Can conflict with #58 which implements cancelling a single activity

- [x] I can mark multiple activities
- [x] The marked activities can be cancelled by clicking a button
- [x] The marked activities can be copied by clicking a button

**Comment by andpaacoke** [comment]
The guardian taps the edit button to enter mark mode which brings up the bottom bar
![Mark mode – 17](https://user-images.githubusercontent.com/22811754/55875037-54f2da80-5b94-11e9-85bf-34086edd5c7b.png)
if no activities are marked the buttons on the bottom bar are disabled
![Mark mode](https://user-images.githubusercontent.com/22811754/55875043-58866180-5b94-11e9-8891-44fb67928326.png)
When activities are marked their borders are highlighted to indicate this
![Mark mode – 8](https://user-images.githubusercontent.com/22811754/55874989-3096fe00-5b94-11e9-8dc4-f1625a0ad7cb.png)
When copying multiple activities you need to be able to choose which day you want to copy the activities to
![Mark mode – 10](https://user-images.githubusercontent.com/22811778/56886988-95959380-6a70-11e9-801f-6d60ec2ca3e2.png)

**Comment by Tekrus** [comment]
@aau-giraf/sw613f19 You have been assigned to this! :)
