### ISSUE TITLE
"Overståede Uger" includes current week

### ISSUE THREAD

**Issue by ggAlexS** [aau-giraf/weekplanner-OLDUI#592]
**Describe the bug**
The current week is included in the "Overståede uger" category.
**To Reproduce**
1. Create weekplan in current week

**Expected behavior**
The current week should not be in the "Overståede uger" category

**Screenshots**
![billede](https://user-images.githubusercontent.com/31063192/95733422-671a7100-0c82-11eb-8e8b-091e8f6352e5.png)

**Environment (please complete the following information):**
- OS: Android 
- Emulator Yes
- Phone [7wsvga Tablet]
- APK Version 30

**Comment by Kaliahh** [comment]
Seems to be a rounding error in weekplan_selector_screen.dart line 153. Uses .round(), works if uses .floor(), but that might cause other problems
