### ISSUE TITLE
As a guardian I would like to be able to log out from the "show activity" screen

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#600]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to log out from the show_activity_screen. 

**Describe the solution you'd like**
Add a log out button to the top right

**Additional context**
![Untitled](https://user-images.githubusercontent.com/42242841/95865309-d1a4dd00-0d66-11eb-9e34-217463a2a69c.png)

**Comment by soenderby** [comment]
This is made irrelevant by #636 and #638
