### ISSUE TITLE
As a guardian I would like for the order of the button in the navigation bar to be consistent

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#601]
**Is your feature request related to a problem? Please describe.**
The log out button shifts whenever there is a settings button. The "change to citizen" button appears between the edit button and the log out button when going from the week plan overview to a specific week plan

**Describe the solution you'd like**
The order on the edit week plan screen should be:
![image](https://user-images.githubusercontent.com/42242841/97427437-cdef8980-1914-11eb-8836-77313d23893e.png)

This way the buttons can be added and taken away without them jumping around.

**Additional context**
Current situation (With log out button that will be removed by #638 ):
![image](https://user-images.githubusercontent.com/42242841/95867982-0a928100-0d6a-11eb-856d-2c22013bdadb.png)
![image](https://user-images.githubusercontent.com/42242841/95868051-1f6f1480-0d6a-11eb-8ebe-faa9f69ecb36.png)
![image](https://user-images.githubusercontent.com/42242841/95868110-3281e480-0d6a-11eb-8935-4e23765c0e93.png)

**Comment by nbhansen** [comment]
closed since new UI
