### ISSUE TITLE
As a guadian I would like for the app to prompt me for access to the Gallery

### ISSUE THREAD

**Issue by dkalaxdk** [aau-giraf/weekplanner-OLDUI#603]
**Is your feature request related to a problem? Please describe.**
When installing the app (On iPad) the user has to manually grant the app access to the Gallery through the settings.

**Describe the solution you'd like**
The app should prompt the user to change the setting, and navigate the user to the settings.

**Additional context**
Potentially see https://developer.apple.com/documentation/photokit/requesting_authorization_to_access_photos
As this might be the fix for the issue.

**Comment by ProgDaniel** [comment]
This issue does not seem to be apparant in iOS version 14/14.1, though it is unknown what version exactly this issue may have been affected on. Because we could not replicate it on these, the issue have been closed.
