### ISSUE TITLE
As a guardian I would like to be able to add a timer to an activity so that the citizen can see how much time is to be spent on this activity

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#61]

**Comment by andpaacoke** [comment]
![Aktivitet - 1](https://user-images.githubusercontent.com/22811754/55874021-6ab2d080-5b91-11e9-800d-19fbc895efbf.png)
![Choose representation 1](https://user-images.githubusercontent.com/22811754/55874025-70101b00-5b91-11e9-8ef7-be4079431cf7.png)
![Aktivitet - 7](https://user-images.githubusercontent.com/22811754/56794953-a398a980-680f-11e9-8ee2-a7645d0137ac.png)
![Aktivitet - 9](https://user-images.githubusercontent.com/22811754/56794956-a72c3080-680f-11e9-9da1-014324e68bad.png)
