### ISSUE TITLE
As a guardian I would like to be able to unmark completed activities

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#616]
**Is your feature request related to a problem? Please describe.**
The current way of unmarking activities as completed, is to cancel the activity and then undo the cancel. This is not ideal.

**Describe the solution you'd like**
There should be a button for unmarking the activity as completed.

**Additional context**
Related to #529 and #615

**Comment by dkalaxdk** [comment]
Closed by #529
