### ISSUE TITLE
Searching pictograms should not be case sensitive

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#622]
**Is your feature request related to a problem? Please describe.**
The pictogram search feature should not be so strict with case

**Describe the solution you'd like**
Searching for, as an example, "k" should yield the same results as "K"

**Additional context**
Current search results for "k" and "K":
![Screenshot_1603196862](https://user-images.githubusercontent.com/42242841/96586148-de827d00-12e0-11eb-9783-fef38c82d4a9.png)
![Screenshot_1603196870](https://user-images.githubusercontent.com/42242841/96586150-dfb3aa00-12e0-11eb-9712-5f7867dd50ac.png)

**Comment by dkalaxdk** [comment]
Solved in aau-giraf/web-api#169
