### ISSUE TITLE
As a guardian I would like to be able to copy a week plan from one citizen to another so that I don’t have to recreate the same schedule twice if two citizens have very similar schedules

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#63]

**Comment by andpaacoke** [comment]
![copy weekplan - choose citizen](https://user-images.githubusercontent.com/22811754/57692506-370f0e80-7647-11e9-9293-fa57d369fa44.png)
![copy weekplan - choose weekplan](https://user-images.githubusercontent.com/22811754/57692518-3eceb300-7647-11e9-8e82-5ac16fe525c4.png)
![copy weekplan - copy weekplan](https://user-images.githubusercontent.com/22811754/57692614-79385000-7647-11e9-8dcb-d98fd86cc9c0.png)
![copy weekplan - choose citizen to copy to](https://user-images.githubusercontent.com/22811754/57692523-42fad080-7647-11e9-9f41-48e0b5eaccc7.png)
![copy weekplan - confirm copy](https://user-images.githubusercontent.com/22811754/57692526-442bfd80-7647-11e9-8250-b987aee955f1.png)
![copy weekplan - plan copied!](https://user-images.githubusercontent.com/22811754/57692527-44c49400-7647-11e9-8790-b7e108e4db28.png)

**Comment by Lortemanden** [comment]
duplicate of issue #325
