### ISSUE TITLE
As a guardian I would like my week plan colour theme to match the citizen's week plan colour theme.

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#630]
**Is your feature request related to a problem? Please describe.**
The guardian's week plan colour theme is always TEACCH, whereas the citizen's week plan colour theme could be something else.

**Describe the solution you'd like**
The guardian's week plan colour theme should match the currently selected theme for the citizen

**Additional context**
Changing the colour theme for the citizen, does not change the colour theme for the guardian:
![ezgif-3-62c61cd1f692](https://user-images.githubusercontent.com/42242841/97428546-69352e80-1916-11eb-97e9-f4ab21ffc8a3.gif)

**Comment by nbhansen** [comment]
closed since new UI
