### ISSUE TITLE
Changing "Tegn for udførelse" does actually change the sign, it is always a check-mark

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#641]
**Describe the bug**
When changing the "Tegn for udførelse", the sign does not change 

**To Reproduce**
1. Open a weekplan
2. Go to settings
3. Change the "Tegn for udførelse" to "Fjern aktiviteten fra borgeren"
4. Go back to the weekplan
5. Complete an activity
6. Observe that is is still a green check-mark

**Expected behavior**
The sign should change based on the set "Tegn for udførelse"

**Actual behavior**
It is always a green check-mark

**Environment (please complete the following information):**
- OS: Android 10
- Emulator
- 8 Foldable API 30

**Comment by dkalaxdk** [comment]
This was not an issue, it just did not update the marker in guardian view, which is not supposed to update.
