### ISSUE TITLE
Unable to delete weekplans that are not yet completed.

### ISSUE THREAD

**Issue by social2dk** [aau-giraf/weekplanner-OLDUI#646]
**Describe the bug**
If you create a weekplan with a date in the past, and then change it to be a future weekplan again, you will "lock" the future weekplans for that user from being deleted, until a weekplan is changed from being a future weekplan to being a finished weekplan.

**To Reproduce**
1. Select a citizen
2. Create a weekplan with a date earlier than the current date, i.e set year to 1111
3. Change the weekplan date to a future date i.e 3333
4. Go to edit mode and try to delete the weekplan and observe that the button gets greyed out as if pressed, but nothing happens on the screen. 
5. Create a new weekplan with a date later then currently, and attempt to delete this, notice that this does not work either.

See comment below for more problems

**Expected behavior**
After changing the date, you should still be able to delete weekplans.

**Actual behavior**
After changing the date i cannot delete weekplans

**Screenshots**
![image](https://user-images.githubusercontent.com/45236436/97549262-7b73a300-19d0-11eb-9814-11c90af511dc.png)

**Environment (please complete the following information):**
- OS: Android
- Emulator
- Pixel 2
- APK Version [e.g. 22]

**Additional context**
When pressing the delete button, a "the method tolist was called on null" exception is thrown. Adding a weekplan to completed weekplans either through creating an entirely new weekplan or by changing the date of one, seems to break this "lock".

**Comment by Kaliahh** [comment]
More problems can be found in #669. That issue is closed, but the bugs are still there, and should be fixed by this issue

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 646](https://trello.com/c/UbDpgd5T/54-issue-646)

**Comment by Emil-Linnebjerg** [comment]
Could not replicate the problem. Neither the sub problems in #669

**Comment by social2dk** [comment]
![bandicam-2020-12-02-10-52-53-179](https://user-images.githubusercontent.com/45236436/100857850-7e5d2a00-348d-11eb-8c0e-5ada8ba47a3a.gif)

Here is a video demonstrating the issue. The reason for going in and out of user after initial deletion, is to avoid a different, unrelated, bug when deleting weekplans. Otherwise this should prove the issue exists. It also seems there's different ways to reproduce it, such as deleting a weekplan in 'overståede uger' then exiting the user and going back in, although this has not been as thoroughly tested.

**Comment by Kaliahh** [comment]
It seems to me like there just has to be no week plans in "Overståede uger", and then the bug appears? As soon as you move one week plan to "Overståede uger" you can delete again.

**Comment by social2dk** [comment]
> It seems to me like there just has to be no week plans in "Overståede uger", and then the bug appears? As soon as you move one week plan to "Overståede uger" you can delete again.

Possibly, although im fairly certain the bug can happen if there are weekplans in "overståede uger" as well. It is also very possible that there are multiple ways to provoke this

**Comment by Kaliahh** [comment]
> > It seems to me like there just has to be no week plans in "Overståede uger", and then the bug appears? As soon as you move one week plan to "Overståede uger" you can delete again.
> 
> Possibly, although im fairly certain the bug can happen if there are weekplans in "overståede uger" as well. It is also very possible that there are multiple ways to provoke this

You are problably right, there may be more ways to provoke it, but at least the bug is consistent when there are no weeks in "Overståede uger".
