### ISSUE TITLE
As a guardian I would like to be able to customize how a completed activity is shown in the week plan for a given citizen, so that it fits their personal preference

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#65]
I would like:

- [ ] A check mark
- [ ] Removal of the activity
- [ ] Making the activity translucent
- [ ] Making the activity greyed out

**Comment by sipman** [comment]
This feature has three main tasks:
- Make the settings screen reflect the options available
- Make a BLoC which has the responsibility  of delegating the data
- Ensure that the API component allows sending the citizen id and not only the authenticated id
- Make the weekplan-screen reflect the chosen option.

**Comment by andpaacoke** [comment]
![image](https://user-images.githubusercontent.com/55434783/77737179-be6e3200-700d-11ea-9cdc-7a438f3ec316.png)
The settings page shown above should go to the menu shown below when the "Tegn for udførelse" is pressed.   
![Marking_Marking](https://user-images.githubusercontent.com/38284952/77742445-c1215500-7016-11ea-8005-81f96d2dc37a.PNG)
Only one of the choices can be choosen. The choosen choice is highligthed with the same yellow as the bar, with a 25% opacity. 

Below is examples on the checkmark, grey out and remove settings viewed form the citizen. This option should not change how a guardian in guardian mode view completed activities.  

![UgeplanCitizen - Completed Checkmark](https://user-images.githubusercontent.com/22811754/55873565-473b5600-5b90-11e9-90a1-1de747d367f1.png)
![UgeplanCitizen - GreyOut](https://user-images.githubusercontent.com/22811754/55873569-4acedd00-5b90-11e9-9afa-98ba278a16cd.png)
![UgeplanCitizen - Remove Completed](https://user-images.githubusercontent.com/22811754/55873573-4c000a00-5b90-11e9-9f4c-d804edfb1225.png)
