### ISSUE TITLE
As a guardian I would like to be able to have pictograms in upper case and lower case

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#652]
**Is your feature request related to a problem? Please describe.**
#531 made it so only the first letter in a pictogram name can be upper case, the rest are made to be lower case.

**Describe the solution you'd like**
Pictograms should be able to be full upper case and full lower case if the guardian wants to.

Related to #711

**Comment by nbhansen** [comment]
closed since new UI
