### ISSUE TITLE
As a guardian I would like to be able to add a new citizen, so that the system is easily set up when a new citizen starts at our institution

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#66]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to add a new citizen.

**Describe the solution you'd like**
The list of citizens should show a function to add a new citizen . When pressed a new window should allow the guardian to take a picture. If no picture is chosen then use the current circle as default.

**Prototypes**
![AddCitizenPrototype1](https://user-images.githubusercontent.com/55434874/76614562-a2a06180-6520-11ea-9149-8d558204ffbd.png)
![Add citizen - Not Done or imp](https://user-images.githubusercontent.com/55434783/76963190-edefb100-6920-11ea-9e2d-1db409b0a727.png)

**Comment by holyfailer** [comment]
It can be found in web-api/GirafRest/wwwroot/admin/ and then main.html.

**Comment by Lortemanden** [comment]
Group 15 has worked on this in sprint 1. 
A pull request has been made and it only needs to be reviewed. 
It should be handed to group 15 to finish in sprint 2.
