### ISSUE TITLE
As a guardian I would like to be able to edit a citizen, so that I can update their picture, name and other citizen specific attributes

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#67]
Guardians should be able to edit the data for citizens.

**Additional context**
See comments below for prototypes

**Comment by andpaacoke** [comment]
From the settings page the guardian can access the citizens settings
![Indstillinger – 1](https://user-images.githubusercontent.com/22811754/57692188-72f5a400-7646-11e9-9ac2-ace247e37671.png)
This takes us to the edit citizen page
![2020e_12_B_GUA_1_WP512 Moving a citizen from one class to another](https://user-images.githubusercontent.com/42242841/101020285-8b9e1580-356e-11eb-9aa9-455b34999fcb.png)
