### ISSUE TITLE
As a guardian I would like for photos added as pictograms to have the same aspect ratio as standard pictograms

### ISSUE THREAD

**Issue by dkalaxdk** [aau-giraf/weekplanner-OLDUI#672]
**Describe the solution you'd like**
As a guardian I would like for photos added as pictograms to have the same aspect ratio as standard pictograms (1:1).
When adding the images, a grey box should appear over the image, showing what will be cropped when uploading the image (Same as on facebook, twitter, and other social media.)

**Comment by nbhansen** [comment]
we decided last year to use the local storage for image handling
