### ISSUE TITLE
As a citizen I would like to be able to make a choice on a choiceboard directly from the week plan

### ISSUE THREAD

**Issue by soenderby** [aau-giraf/weekplanner-OLDUI#673]
**Is your feature request related to a problem? Please describe.**
Currently, in order to make a choice on a choice board, a citizen has to press the choice board in the week plan, then select an activity in the resulting popup, followed by another popup asking for confirmation (Currently with text! See #689)

**Describe the solution you'd like**
A citizen should be be able to choose, by clicking on their chosen activity on the choice board directly from the week plan screen. There should not be any popup asking for confirmation.

This approach should be added as a settings option, the current implementation might be useful for some children.

**Describe alternatives you've considered**
No alternatives considered, as this is an alternative to an already existing feature.

**Comment by JakobTopholt** [comment]
Formerly SW3 was assigned to this issue, but could not complete it.

It was placed back in the sprint backlog for another group to potentially pick it up.
