### ISSUE TITLE
As a user I would like for the check mark and cross to be more distinct

### ISSUE THREAD

**Issue by MichelleTerpling** [aau-giraf/weekplanner-OLDUI#674]
**Describe the solution you'd like**
When marking an activity as complete or cancelled the check mark and cross on the activity should have a black border to make sure that it is always distinct from the pictogram.

**Additional context**
![Screenshot_1605186045](https://user-images.githubusercontent.com/43985811/98943469-d4bef480-24ef-11eb-8918-dddc46bcaefc.png)

**Comment by Kaliahh** [comment]
# Prototype
Add a border to the figures. The prototype uses 2pt, but that might be too much, or not enough.

![2020e_27_GUA_1_WP674 More distinct check mark and cross](https://user-images.githubusercontent.com/42242841/100862996-3097f000-3494-11eb-8c67-d949195c078f.png)
![2020e_27_GUA_2_WP674 More distinct check mark and cross](https://user-images.githubusercontent.com/42242841/100863002-31308680-3494-11eb-8868-998e4c70df49.png)
