### ISSUE TITLE
As a citizen I would like to be able to mark an activity as complete directly from the week plan

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#675]
## Description
**Describe the Task** 

As a citizen, I should be able to mark an activity as complete from the week plan, so I don't need to access the activity screen. I should also be able to start an activity with a timer from the week plan, and it should auto-complete when the timer runs out. 

**Possible Suggested Solution**  
Change so the citizen is not able to access the activity page anymore. Instead, they will look at activities in the current week plan. They will, from here, be able to mark activities as complete and start timers which will auto-complete when the time runs out. 

Potentially in the future, add an option that allows a guardian to decide if a citizen should be able to access the activity screen.

**Comment by danielalexlarsen** [comment]
Issue #400 will be opened again and replaced with this one, more detailed and links to current issues still not fixed hehe
