### ISSUE TITLE
As a citizen I would like to be able to start a timer directly from the week plan

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#678]
**Describe the solution you'd like**
If the citizen has the "Lås tidsstyring" option set to true, clicking on an activity with a timer should start the timer. When the timer is done, clicking on the activity again should complete it.

There should be an additional settings option for this, as some children might not want to start the timer when clicking on the activity, and just complete it instead. Those children might instead use a physical hourglass, and just use the timer in the week plan to indicate that they should find an hourglass. 

Multiple options for how to show that the timer is going should be looked at:
- Making the timer appear in a popup that fills the screen.
- Making the timer icon on the activity animated. It should probably be enlarged so that the children can see it more clearly, but it should also be considered that this might hide too much of the pictogram. Experiment.

Alternatively, you could also experiment with letting the citizen click on the timer icon on the activity. For this to work, the icon definitely needs to be bigger, so be careful not to cover the pictogram too much.

Heavily related to #675

**Comment by nbhansen** [comment]
we decided last year to kill timers for now
