### ISSUE TITLE
As a guardian I would like to be able to switch to and from the citizen view from the activity screen

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#680]
**Describe the solution you'd like**
There should be a button to switch mode on the activity screen in both citizen and guardian view

Related to #711

**Comment by dkalaxdk** [comment]
**Prototype:**
Add this button
![2019f_7_CIT_2_WP2_LI](https://user-images.githubusercontent.com/13720707/100993580-7e246380-354d-11eb-9461-6466cba099ed.jpg)
