### ISSUE TITLE
Scope: App should always run in horizontal mode and for now require a 10ish tablet to use

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#690]
**Is your feature request related to a problem? Please describe.**
The app looks really squished and bad on a phone with low resolution in vertical mode.

**Describe the solution you'd like**
The app should detect if it is being used on a phone, and force horizontal mode. The team that implements this should go through the entire app and create issues for where the app looks bad even in horizontal mode.

**Alternative solution**
Go through the entire app and make sure that it looks good in vertical mode. This would entail making a lot of things sideways scrollable. 

**Additional context**
Examples from a Google Pixel:

In a week plan:
![Screenshot_1606398388](https://user-images.githubusercontent.com/42242841/100358861-0dce8d00-2ff7-11eb-8538-513f7304db4a.png)

When editing a choice board:
![Screenshot_1606398459](https://user-images.githubusercontent.com/42242841/100358865-0effba00-2ff7-11eb-9ca4-152a6260c79b.png)

**Comment by nbhansen** [comment]
for now there seems to be very few usecases where really NEED it to work on mobile phones and various devices - at least the two external stakeholders all run on (at least) 10 inch tablets. For now, we focus on getting that to work, make a new issue if phone functionality becomes required or useful.
