### ISSUE TITLE
As a guardian I would like for the list of citizens to be sorted by their name

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#697]
**Describe the solution you'd like**
Just sort the citizens by name, instead of time of creation. 

**Additional context**
This is a mess to navigate
![Screenshot_1606987190](https://user-images.githubusercontent.com/42242841/100989486-369fd680-3551-11eb-9fdb-02f15e1b9b26.png)

**Comment by FrederikBendix** [comment]
Det virker til, at citizens allerede bliver sorteret alfabetisk på navn. Diskuter til PO-møde
