### ISSUE TITLE
Timer does not get removed when a timer is running

### ISSUE THREAD

**Issue by Rosmarium** [aau-giraf/weekplanner-OLDUI#703]
**Describe the bug**
If a timer has been added to an activity, the timer and add choice board buttons do not disappear when clicking on done.

**To Reproduce**
1. Go to 'an activity'
2. Click on 'Timer'
3. Click on 'Done'

**Expected behavior**
The timer should disappear as is the case when the timer has not been added.

**Actual behavior**
The timer does not disappear.

**Additional context**
It is most likely a problem in show_activity_screen, when the timer is added it doesn't check for the completed state of the activity when building the timer.

**Comment by Kaliahh** [comment]
Was this fixed by #266? @Rosmarium

**Comment by Kaliahh** [comment]
Fixed by #266
