### ISSUE TITLE
Redesign activity screen

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#711]
**Is your feature request related to a problem? Please describe.**
The activity screen has been filled with features that are inconsistent in their design. This should be rectified with a unified design.

**Describe the solution you'd like**
- The keyboard should not cover the textbox when renaming choice boards and activities. Move the name field to be on top of the pictogram, away from the keyboard. 
- When renaming an activity or choice board, the cursor should start at the end, and the user should have to delete the previous name if they want to completely change the name. This will allow the user to make small changes to the name, without having to write the whole name again.
  - There should be no save button exclusively for the name.
  - The "Hent standard" button should be small and to the right of the name field.
- The case that is written in the name field should actually be saved. You should be able to name an activity "Løbe", "løbe", "løBe", "LØBE", or "LøBe", if you want to. See #652 
  - The standard should start with uppercase and have the rest lower case. 
- Remove the back button in the top left.
- Add a cancel and save button to where the back button was before. These buttons should go back to the week plan view. Save should save all changes. Cancel should make a popup appear, asking if the user wants to cancel all changes. If yes, go back to the week plan view, if no, remove popup and stay on the activity screen with the changes still there. 
  - Both buttons should an icon. A floppy disk for save, and a cross for cancel.
- Add a "switch to citizen" button to the top bar. See #680 
- Both the "Aflys" and the "Færdiggør" knap should have text and an icon (see #679). A red cross for the "Aflys" button and a green checkmark for the "Færddigør" button.
- When there are more than 4 choices in a choice board, a scroll bar should be visible in the choice board, and the user should be able to scroll through the choices. See #637 
- The standard name for a choice board should be "Valg" and the button should be called "Tilføj valg".
- There should be no "Færdiggør" button when the user has added a choice and made the activity a choice board. You cannot finish a choice board, only activities. See #691 

**Additional context**
Prototypes

**Comment by Kaliahh** [comment]
## The start of a prototype:
![image](https://user-images.githubusercontent.com/42242841/102222345-98fabe80-3ee3-11eb-9552-5a755ec3b892.png)

**Comment by nbhansen** [comment]
closed since new UI
