### ISSUE TITLE
As a guardian I would like for the “Lås tidsstyring” in the settings of the week plan to be set to true by default

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/weekplanner-OLDUI#725]
**Is your feature request related to a problem? Please describe.**
Most children should not be able to pause and stop their timers, but by default they all can. This would require that the guardian always goes in and sets that option to false.

**Describe the solution you'd like**
Set the "Lås tidsstyring" to be true by default

**Comment by kristnaKris** [comment]
Issue copied to API repository as the solution is to be made there. New issue number is [#186](https://github.com/aau-giraf/web-api/issues/186) on the api repository.
