### ISSUE TITLE
The Continuous Integration job: iOS on macos-latest always fails

### ISSUE THREAD

**Issue by JakobFaarGreg** [aau-giraf/weekplanner-OLDUI#736]
**Describe the bug**
In GitHub Actions, in the Continuous Integration the iOS build-and-test fails every time.
The error is: `{
  "errors" : [ {
    "id" : "V7YVQUJUERMVLNH47QKVIEHWPA",
    "status" : "403",
    "code" : "FORBIDDEN.REQUIRED_AGREEMENTS_MISSING_OR_EXPIRED",
    "title" : "A required agreement is missing or has expired.",
    "detail" : "This request requires an in-effect agreement that has not been signed or has expired.",
    "links" : {
      "see" : "/agreements"
    }
  } ]
}`

**To Reproduce**
1. Commit some changes
2. Attempt to push
3. This is where it crashes after approx. 10 minutes.

**Expected behavior**
The Continuous Integration should succeed.

**Actual behavior**
The commits are never pushed to the remote branch.

**Screenshots**
![image](https://user-images.githubusercontent.com/56345889/134314748-58deaf0b-36ef-47ef-9905-1ec867572ed5.png)
![image](https://user-images.githubusercontent.com/56345889/134314829-8a6eeff1-8cea-4600-8dd4-24a64f8c9633.png)
![image](https://user-images.githubusercontent.com/56345889/134315487-955c8acc-4570-431a-9cf8-4cf6a8c26bb1.png)

**Environment**
- OS: Windows 10
- Emulator: Pixel C, Tablet, API 30, Android 11, x86_64
- APK Version:  Flutter 2.0.5, Dart 2.12.3

**Comment by Brandhoej** [comment]
# The issue and solution
I assume the problem to be caused by an **Apple Developer Program License Agreenment update**, which requries Ulriks *confirmation* - this can be seen on the following image:
<img width="1434" alt="appstoreconnect_2" src="https://user-images.githubusercontent.com/58144556/134479060-b0aea289-5f1d-4bd1-b5c7-b2ad1f47de56.png">

More detailed the cause of the error can be seen on the following image, where the workflow attempts to download the provisioning profile.
![github_action_error](https://user-images.githubusercontent.com/58144556/134479420-9bbea23d-e62e-42d2-b258-e3291233af67.png)

Here the authorized http status (*403*), *detail*, and *title* supports the previous assumption.

## Additional information

When looking at the workflow we can see the secrets which are in use:
![workflow](https://user-images.githubusercontent.com/58144556/134479540-e479c9d5-f0d0-48c1-9e46-d0123fb24d13.png)
The secrets however are not the cause. The reason behind this is that the agreement is *active* until May 14, 2022.
<img width="1429" alt="appstoreconnect_3" src="https://user-images.githubusercontent.com/58144556/134479729-3a5e6109-a918-4eb4-838f-c71a9a89eb2c.png">

**Comment by Brandhoej** [comment]
Weekplanner provisioning profiles is now successful and writes "IOS_APP_STORE" correctly. But now the following errors appear:

```console
error: No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "3PDH9946T4" with a private key was found. (in target 'Runner' from project 'Runner')

error: Provisioning profile "Weekplanner Release" expired on Apr 28, 2021. (in target 'Runner' from project 'Runner')
```

I believe that the  ```secrets.APPSTORE_ISSUER_ID```, ```secrets.APPSTORE_API_KEY_ID```, and ```secrets.APPSTORE_API_PRIVATE_KEY``` might be at fault. I will talk with the Apple Developer and ask for new ones.

**Comment by Brandhoej** [comment]
Soooo. I now believe that the secrets are not the cause of the issues (Or maybe later).
I discovered the website for [apple developers](https://developer.apple.com/), and here i found our provisioning profile which expired on Apr. 28, 2021 as stated in the [second error](https://github.com/aau-giraf/weekplanner/issues/736#issuecomment-927696930):

> ```
> error: Provisioning profile "Weekplanner Release" expired on Apr 28, 2021. (in target 'Runner' from project 'Runner')
> ```

The provisioning profiles tab can be seen on the image below.
![apple_developer_provisioning_profiles](https://user-images.githubusercontent.com/58144556/135061566-af81e952-4693-4ea5-b296-42fe844f53fe.png)
On this image we can see the "Giraf Release" provisioning profile which is expired... When inspecting this profile we see what is in the image below:
![apple_developer_provisioning_profile](https://user-images.githubusercontent.com/58144556/135061738-c9106204-c6d6-409f-9ffb-2471fca9719b.png)
As one can see there is a total of **one** certificate assigned to it. **This certificate is new and created by me today**, I believe this certificate will renew the provisioning profile. But even though the certificate is assigned to the provisioning profile it is still expired.

I am not sure why this is the case. Inspecting the certificates on the same [apple developers](https://developer.apple.com/) website:
![apple_developer_certificates](https://user-images.githubusercontent.com/58144556/135062147-66d6a178-3f8a-4756-856d-10c1c79570c2.png)
We can see that there are *a lot* of certificates. *I don't know what their uses are*. Inspecting the certificate i just created:
![developer_apple_certificate](https://user-images.githubusercontent.com/58144556/135062273-3524db01-c54c-4291-83e9-95b15730f007.png)
Nothing seems wrong, and even when they are compared with the others, it seems fine. **However, now to the current issue**. The certificate **MUST** be signed on a mac (I have Windows and Linux), but i had access to one. The certificate i created correctly resulted in a public/private key and when downloading the created certificate (as seen on the image above) it installed locally on the mac correctly. This can be seen on the image below:
![public_private_certificate](https://user-images.githubusercontent.com/58144556/135062593-f1c400f2-c1f2-47d2-ab72-85320fb86bad.png)
This all look fine! but wait! No?!?!? 
![apple_development_certificate](https://user-images.githubusercontent.com/58144556/135062664-2068dd74-271e-4caf-902b-9472758613d7.png)
The certificate has not been verified/accepted yet :1st_place_medal: :cry: 
I have talked with Apple Support they could not help me :disappointed:. I have now contacted Developer Apple Support but they have an expected 1-2 business days wait :crying_cat_face:.

The current trajectory: I might attempt to create a new provisioning profile to check if the certificate issue is a special case. Meanwhile, i am waiting for a response from support.

**Comment by Brandhoej** [comment]
I just saw the "Godkend" dropdown on the image found in the previous reply:
> ![apple_development_certificate](https://user-images.githubusercontent.com/58144556/135062664-2068dd74-271e-4caf-902b-9472758613d7.png)
I checked "Godkend alt", and it is now accepted for "this" account, as seen on the image below:
![apple_developer_certificate_accepted](https://user-images.githubusercontent.com/58144556/135083139-51a40035-9cb8-4287-aa38-e45d5c5b1a6f.png)

The *provisining profile* is still expired. For this reason the previous trajectory is still the current:
> The current trajectory: I might attempt to create a new provisioning profile to check if the certificate issue is a special case. Meanwhile, i am waiting for a response from support.

**Comment by Brandhoej** [comment]
It is now done and dandy!!!!!!!!!!!

![image](https://user-images.githubusercontent.com/58144556/136172311-2cb13609-69e4-496b-9f77-d1e67aa44d66.png)

*The solution* was to create a new **IOS distribution certificate** which is actually pretty simple, but there is **NO** documentation and/or tutorial for it.

Here the quick person, can notice that i previously attempted to create *Apple Development certificates*, which should have been **IOS distribution certificate** instead. For this reason i could not select the created certificate under the provisioning profile used by GIRAF. However, no information about the required certificate was stated ANYWHERE.

1. Create the certificate request following this tutorial:
https://www.youtube.com/watch?v=oK1b-H6rh08
2. Create the certificate with the type of **IOS distribution**
3. Use it with the provisioning profile.

It was a fun run. :cry:

**Comment by Brandhoej** [comment]
A new issue regarding the same profile has been encountered:
>  error: No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "3PDH9946T4" with a private key was found. (in target 'Runner' from project 'Runner')

from [run](https://github.com/aau-giraf/weekplanner/pull/732/checks?check_run_id=3813067412)

**Comment by Brandhoej** [comment]
An additional issue regarding the workflow is also:
> warning: [options] source value 7 is obsolete and will be removed in a future release

From [run](https://github.com/aau-giraf/weekplanner/pull/732/checks?check_run_id=3813067627)
Solution might be [this](https://stackoverflow.com/questions/64791058/warning-options-source-value-7-is-obsolete-and-will-be-removed-in-a-future-re)

**Comment by Brandhoej** [comment]
Regarding [comment](https://github.com/aau-giraf/weekplanner/issues/736#issuecomment-935889376) additional resources are:
  - [blog.codemagic.io](https://blog.codemagic.io/how-to-code-sign-publish-ios-apps/)
  - [developer.apple.com](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html)
