### ISSUE TITLE
As a citizen I would like to be able to mark an activity as done so that I know how far along in my day I am

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#75]
This is related to #58 but a citizen should not be able to mark as cancelled

Tasks:
- [x] Create or reuse BLoC that allows marking an activity as done
- [x] Add a button to view activity that allows marking an activity to done

This is blocked by #45

**Comment by andpaacoke** [comment]
Prototype views for reference
![Aktivitet - 1 –  Citizen](https://user-images.githubusercontent.com/22811754/55873345-b1073000-5b8f-11e9-947a-b2271e3c13db.png)
![Aktivitet done - 1 –  Citizen](https://user-images.githubusercontent.com/22811754/55873436-f592cb80-5b8f-11e9-9847-4698f34e0937.png)
