### ISSUE TITLE
Not able to remove alternate name

### ISSUE THREAD

**Issue by Sijmon** [aau-giraf/weekplanner-OLDUI#798]
## Description
**Describe the bug** \
When changing a name of a pictogram for a citizen, an alternate name is added to the database, consisting of the reference between the citizen, the pictogram and the alternate name. This works, but you are not able to remove this alternate name again.

**To Reproduce**
1. Go to weekplan screen
2. Click on a pictogram
3. Write a new name/discription of this pictogram
4. Click on "gem til borger"

Now when clicking on "hent standard" the name of the pictogram is changed to the default, but only for this specific pictogram and not for other places where this pictogram is used for this citizen. You are however able to type the default name in the input field youself, and click on "gem til borger", and this will make it so every future usage of this pictogram for this citizen, will have the default name, but the alternate name still exists in the database, with it's alternate name just being the default name (which does not make sense, as it is no longer an alternate name then)

**Expected behavior** \
I would expect the alternate name to be removed from the database either right after clicking on "hent standard", or by clicking on "hent standard" and thereafter clicking on "gem til borger".

**Actual behavior and screenshots** \
Right now when clicking on "hent standard", the name of the pictogram are changed to the default instantaneous, without being able to confirm the change first (this could be fine, but it is something to take into considerations). Also, this does not have an effect on the alternate name as described previously, so all future activities which uses this pictogram, will still use the alternate name stored in the database.
![alternameNameError](https://user-images.githubusercontent.com/58163499/139255645-a071e543-3c75-470f-90d0-17fe20bb972c.png)

The issues with this bug is that it uses unnecessary memory in the database, and also there does not exist an intuitive way to use the default name of a pictogram in every future usages, other than updating the alternate name to use the default name (instead of this, the alternate name should just be removed)

## Sub Tasks
*Create your own subtask issues on GitHub and link them here in a list.*
- [ ] \<Subtask link>

**Comment by JonasStjerne** [comment]
@Jaffenheimer @JakobTopholt After looking a bit more into the current database architecture, we've become unsure about the expected behavior.

- Should a pictogram for a user share the same name for all activities?
- If a pictogram is given an alternate name, should all other previously made pictograms of that kind be renamed?
- If not, what would the behavior be like?

Thanks

**Comment by MarcMData** [comment]
Continuing this in issue #874
