### ISSUE TITLE
Load configuration from configuration file

### ISSUE THREAD

**Issue by TobiasPalludan** [aau-giraf/weekplanner-OLDUI#83]
Should have a standard configuration.template file that is version controlled, and which every developer should copy (and remove template from) in order to setup the environment.
It should be split into a local and a production file.

Configuration file should include:
- debug [true/false]
  - Used for showing/hiding the 'autofill and login' button
- Server base url [textstring]
  - So we can use a production database and a localhost database

More might be added.

Find inspiration in Laravel .env files or Angular's environment.ts files.

**Comment by thomaslhansen** [comment]
This issue is still relevant since hard coded urls are still within the code and should be avoided at all cost.

**Comment by Tricky12321** [comment]
This is no longer the case.
This will be fixed along #47 
Its all ready on https://github.com/aau-giraf/weekplanner/tree/flutter/feature_047_choose_citizen

**Comment by Tricky12321** [comment]
#87
