### ISSUE TITLE
As a developer I would like a button widget so that I do not have duplicated code and waste time

### ISSUE THREAD

**Issue by Eduardsen** [aau-giraf/weekplanner-OLDUI#85]
The buttons should follow the guidelines defined in the design guide.

**Comment by andpaacoke** [comment]
Pressed button
![Button pressed](https://user-images.githubusercontent.com/22811754/55873184-3f2ee680-5b8f-11e9-89fa-c67f3e2ab76e.png)
Default button
![Button default](https://user-images.githubusercontent.com/22811754/55873190-40f8aa00-5b8f-11e9-9a2a-4b81f3cc4522.png)
Disabled button
![Disabled](https://user-images.githubusercontent.com/22811754/55873193-4524c780-5b8f-11e9-8d45-4292303675c9.png)
