### ISSUE TITLE
As a guardian, I would like to assign a picture to a Citizen upon creation, so that I can more easily identify the citizen.

### ISSUE THREAD

**Issue by manfredhod** [aau-giraf/weekplanner-OLDUI#856]
## Description
**Describe the Task** \
When a Guardian is creating a new Citizen account, they should be able to attach a picture to the given Citizen to identify the Citizen more easily. 

- As of now, the front-end functionality in Weekplanner is almost implemented. When creating a Citizen account, the Guardian is able to choose an image from their gallery or take a picture with their camera, which is then displayed in the New Citizen Screen.
- The database also has attribute needed for uploading the image in the table for users called 'aspnetuserroles' with the attribute 'UserIcon' (type is longblob) 

![Image](https://user-images.githubusercontent.com/26058672/195823549-0aec0d94-dd99-43e2-b91d-f055055bd779.png)

- Missing back-end functionality for uploading the chosen image to the server, saving it in the database, and retrieving it for display on the Choose Citizen Screen.

Weekplanner branch: https://github.com/aau-giraf/weekplanner/tree/feature/856
Api_client branch: https://github.com/aau-giraf/api_client/tree/feature/856

**Possible Suggested Solution**  
- Retrieve the image from the new_citizen_bloc, upload it with the rest of the data for the new Citizen through the api client, and store it in the 'UserIcon' column in 'aspnetuserroles' in the database
- When loading user images, retrieve these from same column

## Sub Tasks
- [x] Add "Tilføj billede" button on the "Ny borger" page
- [x] Add "Tag billede" button on the "Ny borger" page
- [x] Add preview of the selected picture on the "Ny borger" page
- [x] When picture is added, still able to change to another picture
- [ ] Retrieve picture from new_citizen_bloc and send to server
- [ ] upload picture to database
- [ ] retrieve user pictures from server
- [ ] display user pictures on the Choose Citizen screen
- [ ] Catch possible exceptions which could occur
- [ ] Write and fix unit tests 
- [ ] Write one or two integration tests
- [ ] If three above substasks are not relevant to your issue explain why

**Comment by andreaslborg** [comment]
This is what the "Ny borger" currently looks like:
![Image](https://user-images.githubusercontent.com/72602768/199667128-07f897cc-9966-4e51-8480-09807ac0e7a2.png)

Two unit tests are still failing.
We have spent a lot of time trying to figure out why they are still failing, but haven't concluded why yet.

![Image](https://user-images.githubusercontent.com/72602768/199248825-559be7f7-eb73-4c00-8892-13c45a2efd73.png)

We believe it has something to do with the gesture method and we know that the test can't find the key ErrorMessageDialog.

If you have any questions, contact us at **cs-22-sw-5-03@student.aau.dk**

**Comment by JakobTopholt** [comment]
The code for taking pictures with the camera can be found under weekplanner/lib/screens/take_picture_with_camera_screen.dart](https://github.com/aau-giraf/weekplanner/search?q=takepicturewithcamera
