### ISSUE TITLE
Weekplanner dependabot alert: http before 0.13.3 vulnerable to header injection

### ISSUE THREAD

**Issue by Jaffenheimer** [aau-giraf/weekplanner-OLDUI#876]
Weekplanner repo. er blevet scannet af Dependabot og fandt (i vores pubspec) at vi bruger en for gammel version af http som indeholder en "http header injection vulnerability". 
https://github.com/aau-giraf/weekplanner/security/dependabot/2

potentiel løsning
Opdater http til at være en version efter 0.13.3, eller "validating request methods". Jeg anbefaler en upgrade. 

Fixed in https://github.com/aau-giraf/weekplanner/pull/896

**Comment by Lildhansen** [comment]
see issue https://github.com/aau-giraf/api_client/issues/110

**Comment by andreaslborg** [comment]
Both Dart SDK and http in pubspec will be updated with flutter upgrade: https://github.com/aau-giraf/weekplanner/pull/896

Without having checked with dependabot, this issue might be resolved with this PR.

**Comment by andreaslborg** [comment]
As suspected, the issues were resolved following the Flutter upgrade https://github.com/aau-giraf/weekplanner/pull/896.
