### ISSUE TITLE
As a trustee/citizen, I should not be able to view the option for adding a new user

### ISSUE THREAD

**Issue by lasse2507a** [aau-giraf/weekplanner-OLDUI#885]
## Description
Currently, all types of users get directed to the screen shown in the screenshot below, where there is an option to add new users. This should only be available for guardians, hence, trustees and citizens should not be able to view the option to register new users.
![issue625_create_citizen](https://user-images.githubusercontent.com/44569984/198214049-ce385a11-78ac-4a08-9b9b-2e1606fe435e.JPG)

**Comment by YusufIA99** [comment]
This issue is being fixed here https://github.com/aau-giraf/weekplanner/pull/878
