### ISSUE TITLE
As a guardian, I would like that the app is fully available offline so that I can still use it if the internet is down

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#9]
The guardians and citizens are sometimes on fieldtrips where internet coverage is limited.

**Comment by Tekrus** [comment]
This is being postponed until the basic functionality of the system is working.

**Comment by T-Dawq** [comment]
Prioritized list of features that should be available offline:
1. Citizen features: Limited to current week.
    1.1  View weekplan.
    1.2  View activity.
    1.3  Mark activity as completed.
    1.4  Timer functionality.
 2. Guardian features: Limited to current week.
    2.1  View weekplan.
    2.2  View activity.
    2.3  Cancel activity.
    2.4  Timer functionality.
    2.5  Edit weekplan.
 3.  Guardian features:
    3.1  Take picture as pictogram.
    3.2  Create/delete weekplans.
    3.3  All functions from point 2 just not limited to the current week.

**Comment by Lortemanden** [comment]
Group 12 has worked with this in sprint 1.
They have made a method guide in branch wiki_issue_155 which is under review.
Group 12 would like to work with finishing this guide in sprint 2.
Implementing the issue can start in sprint 2. It would be optimal to split this issue into smaller issues.
