### ISSUE TITLE
As a Guardian or Trustee, I would like fully fletched settings menu, so that i can change all the settings regarding my account in the same place

### ISSUE THREAD

**Issue by Jaffenheimer** [aau-giraf/weekplanner-OLDUI#923]
As a Guardian or Trustee, I would like fully fletched settings menu, so that i can change all the settings regarding my account in the same place.
Currently some settings like changing username and password can be done in a settings menu exclusively for a guardian or trustee account while other settings regarding the account in question can only be changed in the settings menu after clicking on a citizen.

## Sub Tasks
- [ ] Move related settings to correct settings menu in the citizen overview

**Comment by nbhansen** [comment]
wont fix not needed
