### ISSUE TITLE
Redesign of 'change username' and 'change password' screens

### ISSUE THREAD

**Issue by emilnormann** [aau-giraf/weekplanner-OLDUI#927]
## Description
Update 'Change username screen' and 'Change password screen' UI wise to fit with the rest of the application. 
Right now the buttons are not Giraf Buttons and the 'Gem' button on the password screen is not fully on the screen while there is empty space above the text fields. 
The top bar when changing password is also in English while it should be in Danish.

This is how it currently looks:
![image](https://user-images.githubusercontent.com/73188508/205643791-e98ddaae-b893-486c-8a20-9e235b6402aa.png)
![image](https://user-images.githubusercontent.com/73188508/205643832-686b50ba-4e41-4cc4-8f06-96fa6dab4cec.png)

**Possible Suggested Solution**  
Update the design and buttons on the screens to better fit Giraf and offer a better user experience.

**Comment by Lyallvaldr** [comment]
Design er lavet. Implementation er i issue 949
