### ISSUE TITLE
Update flutter to start with

### ISSUE THREAD

**Issue by Just1Per** [aau-giraf/weekplanner-OLDUI#938]

**Comment by JakobTopholt** [comment]
Updating flutter early on in the project ensures a better foundation for development, as fewer conflicts will occur the fewer versions  are between the current one and the newest one. The guide for updating Flutter should be on the wiki, I will not add the link here, to save myself time.

**Comment by jsondergaard** [comment]
Prøv lige at se mit seneste commit i "task/938" – jeg har rettet 100 fejl ud af 2400.

Jeg tror ikke det er muligt, uden at et hold skal bruge nærmest alle sprints på det.
