### ISSUE TITLE
Design the views different

### ISSUE THREAD

**Issue by Just1Per** [aau-giraf/weekplanner-OLDUI#939]
This Issue regards the usability test done by the students of 2022 Giraf since feedback from the stakeholders was given.

The test subject made it very clear that it was very confusing to figure out which view the person was in.

So feedback was given regarding a change in color or a description of what view you are in.

As seen in the picture there needs to be a distinction between whether you are viewing it from the citizen's view or the guardian's view, and as well add some distinction from the trustee.

![Image](https://user-images.githubusercontent.com/103027400/206442691-a5083c71-f92b-4951-b5e6-0dc5e935f730.png)

**Comment by JakobTopholt** [comment]
Which color did the test subject, if they did, suggest to indicate which roles? @Just1Per ?

**Comment by JakobTopholt** [comment]
And do you find it appropriate to crate a protoype first? If so there should be an issue under "UI / Protoyping" detailing how it should look, and said protoype should then be added to the design guide on the website https://aau-giraf.github.io/wiki/UI_Design/ .

**Comment by Lyallvaldr** [comment]
Design er lavet. Implementation er i issue 950
