### ISSUE TITLE
Settings tab button to change to activity only view

### ISSUE THREAD

**Issue by Chris31415926** [aau-giraf/weekplanner-OLDUI#944]
As of now you can only change to ShowOnlyActivities view for a citizen, by manually changing it in the database.

Therefor there should be implemented a button in the settings tab that change the boolean in the database, such that a citizen will only be showed activities for the current day.

Furthermore, there should also be implemented a button that changes the number of activities that are to be displayed, when this view is active.

![Image](https://github.com/aau-giraf/weekplanner/assets/10807534/3fb8a346-ddd9-438d-b89e-4f424418f834)

---

Settings modal is located in: api_client/lib/models/settings_model.dart

![Image](https://github.com/aau-giraf/weekplanner/assets/10807534/0e1ff16d-ff6f-44d8-aff1-b925e8a9b980)

---

Api integration is located in: weekplanner/lib/blocs/settings_bloc.dart

Has the following functions:

`loadSettings(DisplayNameModel user)`
`loadSettingsGirafUser(GirafUserModel user) `
`updateSettings(String userId, SettingsModel settingsModel)`
`deleteUser(String userId)`
`setTheme(GirafTheme theme)`
`dispose()`

---

Settings screen is located in: weekplanner/lib/screens/settings_screens/settings_screen.dart

**Comment by M05F3T** [comment]
1
