### ISSUE TITLE
Make API a library on its own

### ISSUE THREAD

**Issue by TobiasPalludan** [aau-giraf/weekplanner-OLDUI#95]
Allows for other apps to use the API.

**Comment by Tekrus** [comment]
@boginw Is this done? The PR is set as merged, but there's a commit that reverts it.

**Comment by TobiasPalludan** [comment]
@Moesgaarda @boginw we had to revert it, as it otherwise would require a rewrite of all tests, so it has a lot of side-effects. This should probably be two or more tasks in the next sprint.
