### ISSUE TITLE
Pictogram Search Bug

### ISSUE THREAD

**Issue by boginw** [aau-giraf/weekplanner-OLDUI#98]
**Describe the bug**
When searching for a pictogram in the pictogram search screen, one can on occasion meet the bug, that crushes all results into a single column and flashes rapidly.

**To Reproduce**
1. Go to PictogramSearch
2. Search for something
3. Search for something else
4. Try to scroll a bit
5. Repeat this and eventually, the fault will show

**Expected behavior**
No flashing and single column

**Actual behavior**
Flashing and single column

**Screenshots**
[video](https://drive.google.com/file/d/16bleafzDT7-jhNdEEvLYcT3CfUTdp2g9/view)

**Environment (please complete the following information):**
- OS: Android
- Emulator: No
- Phone: Samsung Galaxy Tab 2
- APK Version: 0

**Additional context**
[original discussion](https://github.com/aau-giraf/weekplanner/pull/90)

**Comment by Lortemanden** [comment]
Could not find the bug.
Tested on:
OS: Android
Emulator: Pixel C API 29 and Pixel 2 API 28
Physical device: Samsung galaxy S 7
